apiVersion: batch/v1
kind: CronJob
metadata:
  name: itassets-cronjob
spec:
  # AWST: 17 min past the hour, 08:00-17:00, Mon-Fri
  schedule: '17 0-8 * * 1-5'
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: itassets-cronjob
              args: ['manage.py', 'check_ascender_accounts']
              envFrom:
                - secretRef:
                    name: itassets-env-uat
