apiVersion: batch/v1
kind: CronJob
metadata:
  name: itassets-cronjob
spec:
  # AWST: 25 min past the hour, 08:00-19:00, Mon-Fri
  schedule: '25 0,2,4,6,8,10 * * 1-5'
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: itassets-cronjob
              args: ['manage.py', 'department_users_sync_ad_data']
              envFrom:
                - secretRef:
                    name: itassets-env-prod
