apiVersion: batch/v1
kind: CronJob
metadata:
  name: itassets-cronjob
spec:
  # AWST: 28/58 min past the hour, 08:00-19:00, Mon-Fri
  schedule: '28,58 0-10 * * 1-5'
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: itassets-cronjob
              args: ['manage.py', 'check_department_users']
              envFrom:
                - secretRef:
                    name: itassets-env-prod
