# Generated by Django 3.2.16 on 2022-11-25 05:16

import django.contrib.postgres.fields
import django.contrib.postgres.fields.citext
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    replaces = [('organisation', '0002_auto_20210615_1036'), ('organisation', '0003_auto_20210618_1207'), ('organisation', '0004_remove_departmentuser_mail_nickname'), ('organisation', '0005_auto_20210716_1139'), ('organisation', '0006_departmentuserlog'), ('organisation', '0007_auto_20210906_0910'), ('organisation', '0008_auto_20211014_0955'), ('organisation', '0009_auto_20211027_1341'), ('organisation', '0010_auto_20211206_0739'), ('organisation', '0011_auto_20220303_1059'), ('organisation', '0012_location_ascender_desc'), ('organisation', '0013_orgunit_ascender_code'), ('organisation', '0014_auto_20220331_1447'), ('organisation', '0015_auto_20220502_0911'), ('organisation', '0016_delete_adaction'), ('organisation', '0017_auto_20220628_1123'), ('organisation', '0018_alter_location_address'), ('organisation', '0019_remove_departmentuser_org_unit'), ('organisation', '0020_delete_orgunit')]

    dependencies = [
        ('organisation', '0001_squashed_0028_remove_costcentre_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='departmentuser',
            name='position_type',
        ),
        migrations.RemoveField(
            model_name='departmentuser',
            name='working_hours',
        ),
        migrations.AddField(
            model_name='departmentuser',
            name='ad_data',
            field=models.JSONField(blank=True, default=dict, editable=False, help_text='Cache of on-premise AD data', null=True),
        ),
        migrations.AddField(
            model_name='departmentuser',
            name='ad_data_updated',
            field=models.DateTimeField(editable=False, null=True),
        ),
        migrations.AddField(
            model_name='departmentuser',
            name='azure_ad_data',
            field=models.JSONField(blank=True, default=dict, editable=False, help_text='Cache of Azure AD data', null=True),
        ),
        migrations.AddField(
            model_name='departmentuser',
            name='azure_ad_data_updated',
            field=models.DateTimeField(editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='departmentuser',
            name='account_type',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(2, 'L1 User Account - Permanent'), (3, 'L1 User Account - Agency contract'), (0, 'L1 User Account - Department fixed-term contract'), (8, 'L1 User Account - Seasonal'), (6, 'L1 User Account - Vendor'), (7, 'L1 User Account - Volunteer'), (1, 'L1 User Account - Other/Alumni'), (11, 'L1 User Account - RoomMailbox'), (12, 'L1 User Account - EquipmentMailbox'), (10, 'L2 Service Account - System'), (5, 'L1 Group (shared) Mailbox - Shared account'), (9, 'L1 Role Account - Role-based account'), (4, 'Terminated'), (14, 'Unknown - AD disabled'), (15, 'Cleanup - Permanent'), (16, 'Unknown - AD active')], help_text='Employee network account status', null=True),
        ),
        migrations.AlterField(
            model_name='departmentuser',
            name='ad_guid',
            field=models.CharField(blank=True, help_text='On-premise AD ObjectGUID', max_length=48, null=True, unique=True, verbose_name='AD GUID'),
        ),
        migrations.AlterField(
            model_name='departmentuser',
            name='title',
            field=models.CharField(blank=True, help_text='Occupation position title (should match Ascender position title)', max_length=128, null=True),
        ),
        migrations.RemoveField(
            model_name='departmentuser',
            name='mail_nickname',
        ),
        migrations.AlterField(
            model_name='departmentuser',
            name='cost_centre',
            field=models.ForeignKey(blank=True, help_text='Cost centre to which the employee currently belongs', limit_choices_to={'active': True}, null=True, on_delete=django.db.models.deletion.PROTECT, to='organisation.costcentre'),
        ),
        migrations.AlterField(
            model_name='departmentuser',
            name='location',
            field=models.ForeignKey(blank=True, help_text='Current physical workplace.', limit_choices_to={'active': True}, null=True, on_delete=django.db.models.deletion.PROTECT, to='organisation.location'),
        ),
        migrations.AlterField(
            model_name='departmentuser',
            name='manager',
            field=models.ForeignKey(blank=True, help_text='Staff member who manages this employee', limit_choices_to={'active': True}, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='manages', to='organisation.departmentuser'),
        ),
        migrations.RemoveField(
            model_name='departmentuser',
            name='org_unit',
        ),
        migrations.AlterField(
            model_name='departmentuser',
            name='active',
            field=models.BooleanField(default=True, editable=False, help_text='Account is enabled within Active Directory.'),
        ),
        migrations.AlterField(
            model_name='departmentuser',
            name='ad_guid',
            field=models.CharField(blank=True, help_text='On-premise Active Directory unique object ID', max_length=48, null=True, unique=True, verbose_name='AD GUID'),
        ),
        migrations.AlterField(
            model_name='departmentuser',
            name='ascender_data_updated',
            field=models.DateTimeField(editable=False, help_text='Timestamp of when Ascender data was last updated for this user', null=True),
        ),
        migrations.AlterField(
            model_name='departmentuser',
            name='assigned_licences',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=254), blank=True, help_text='Assigned Microsoft 365 licences', null=True, size=None),
        ),
        migrations.AlterField(
            model_name='departmentuser',
            name='azure_guid',
            field=models.CharField(blank=True, editable=False, help_text='Azure Active Directory unique object ID', max_length=48, null=True, unique=True, verbose_name='Azure GUID'),
        ),
        migrations.AlterField(
            model_name='departmentuser',
            name='dir_sync_enabled',
            field=models.NullBooleanField(default=None, help_text='Azure AD account is synced to on-prem AD'),
        ),
        migrations.AlterField(
            model_name='departmentuser',
            name='email',
            field=django.contrib.postgres.fields.citext.CIEmailField(editable=False, help_text='Account email address', max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='departmentuser',
            name='ascender_data',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=dict, editable=False, help_text='Cache of staff Ascender data', null=True),
        ),
        migrations.AlterField(
            model_name='departmentuser',
            name='given_name',
            field=models.CharField(blank=True, help_text='First name', max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='departmentuser',
            name='name',
            field=models.CharField(max_length=128, verbose_name='display name'),
        ),
        migrations.AlterField(
            model_name='departmentuser',
            name='surname',
            field=models.CharField(blank=True, help_text='Last name', max_length=128, null=True),
        ),
        migrations.RemoveField(
            model_name='costcentre',
            name='admin',
        ),
        migrations.RemoveField(
            model_name='costcentre',
            name='business_manager',
        ),
        migrations.AlterField(
            model_name='costcentre',
            name='manager',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='manage_ccs', to='organisation.departmentuser'),
        ),
        migrations.RemoveField(
            model_name='costcentre',
            name='tech_contact',
        ),
        migrations.AlterField(
            model_name='departmentuser',
            name='manager',
            field=models.ForeignKey(blank=True, help_text='Staff member who manages this employee', limit_choices_to={'active': True}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='manages', to='organisation.departmentuser'),
        ),
        migrations.AlterField(
            model_name='orgunit',
            name='manager',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='organisation.departmentuser'),
        ),
        migrations.RemoveField(
            model_name='location',
            name='bandwidth_url',
        ),
        migrations.RemoveField(
            model_name='location',
            name='email',
        ),
        migrations.RemoveField(
            model_name='location',
            name='manager',
        ),
        migrations.RemoveField(
            model_name='location',
            name='url',
        ),
        migrations.RemoveField(
            model_name='departmentuser',
            name='username',
        ),
        migrations.AddField(
            model_name='location',
            name='ascender_desc',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='departmentuser',
            name='ascender_data',
            field=models.JSONField(blank=True, default=dict, editable=False, help_text='Cache of staff Ascender data', null=True),
        ),
        migrations.AlterField(
            model_name='departmentuser',
            name='dir_sync_enabled',
            field=models.BooleanField(default=None, help_text='Azure AD account is synced to on-prem AD', null=True),
        ),
        migrations.CreateModel(
            name='DepartmentUserLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('log', models.JSONField(default=dict, editable=False)),
                ('department_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organisation.departmentuser')),
            ],
        ),
        migrations.AddField(
            model_name='orgunit',
            name='ascender_clevel',
            field=models.CharField(blank=True, max_length=128, null=True, unique=True),
        ),
        migrations.DeleteModel(
            name='ADAction',
        ),
        migrations.RemoveField(
            model_name='costcentre',
            name='org_position',
        ),
        migrations.AlterField(
            model_name='location',
            name='address',
            field=models.TextField(blank=True),
        ),
        migrations.DeleteModel(
            name='OrgUnit',
        ),
    ]
