# Generated by Django 2.0.4 on 2018-05-04 01:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organisation', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='departmentuser',
            options={},
        ),
        migrations.AlterField(
            model_name='departmentuser',
            name='name',
            field=models.CharField(db_index=True, help_text='Format: [Given name] [Surname]', max_length=128),
        ),
    ]
