# Generated by Django 2.2.24 on 2021-06-15 02:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organisation', '0001_squashed_0028_remove_costcentre_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='departmentuser',
            name='position_type',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(0, 'Full time'), (1, 'Part time'), (2, 'Casual'), (3, 'Other')], help_text='Employee position working arrangement (Ascender employment status)', null=True),
        ),
        migrations.AlterField(
            model_name='departmentuser',
            name='working_hours',
            field=models.TextField(blank=True, help_text='Description of normal working hours', null=True),
        ),
    ]
