# Generated by Django 3.2.23 on 2024-01-30 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organisation', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='costcentre',
            name='division_name',
            field=models.CharField(blank=True, choices=[('BCS', 'DBCA Biodiversity and Conservation Science'), ('BGPA', 'Botanic Gardens and Parks Authority'), ('CBS', 'DBCA Corporate and Business Services'), ('CPC', 'Conservation and Parks Commission'), ('ODG', 'Office of the Director General'), ('PWS', 'Parks and Wildlife Service'), ('SG', 'Strategy and Governance'), ('RIA', 'Rottnest Island Authority'), ('ZPA', 'Zoological Parks Authority')], max_length=128, null=True),
        ),
    ]
