# Generated by Django 2.0.4 on 2018-05-03 02:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organisation', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='departmentuser',
            options={},
        ),
    ]
