# Generated by Django 4.2.21 on 2025-05-20 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organisation', '0002_alter_departmentuser_active_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='departmentuser',
            name='last_signin',
            field=models.DateTimeField(editable=False, help_text='Entra ID last sign-in time', null=True),
        ),
        migrations.AlterField(
            model_name='departmentuser',
            name='azure_guid',
            field=models.CharField(blank=True, help_text='Azure Entra ID unique object ID', max_length=48, null=True, unique=True, verbose_name='Azure GUID'),
        ),
    ]
