# Generated by Django 2.0.6 on 2018-07-26 05:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organisation', '0002_auto_20180504_0914'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='secondarylocation',
            name='location',
        ),
        migrations.RemoveField(
            model_name='secondarylocation',
            name='manager',
        ),
        migrations.RemoveField(
            model_name='orgunit',
            name='secondary_location',
        ),
        migrations.AddField(
            model_name='departmentuser',
            name='location',
            field=models.ForeignKey(blank=True, help_text='Current place of work.', null=True, on_delete=django.db.models.deletion.PROTECT, to='organisation.Location'),
        ),
        migrations.AlterField(
            model_name='departmentuser',
            name='secondary_locations',
            field=models.ManyToManyField(blank=True, help_text='Only to be used for staff working in additional loactions from their cost centre', related_name='departmentuser_secondary', to='organisation.Location'),
        ),
        migrations.AlterField(
            model_name='location',
            name='manager',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='location_manager', to='organisation.DepartmentUser'),
        ),
        migrations.DeleteModel(
            name='SecondaryLocation',
        ),
    ]
