# Generated by Django 4.2.10 on 2024-02-23 02:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("organisation", "0002_alter_costcentre_division_name"),
    ]

    operations = [
        migrations.DeleteModel(
            name="OrgUnit",
        ),
    ]
