# Generated by Django 2.2.24 on 2021-06-18 04:07

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organisation', '0002_auto_20210615_1036'),
    ]

    operations = [
        migrations.AddField(
            model_name='departmentuser',
            name='ad_data',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, editable=False, help_text='Cache of on-premise AD data', null=True),
        ),
        migrations.AddField(
            model_name='departmentuser',
            name='ad_data_updated',
            field=models.DateTimeField(editable=False, null=True),
        ),
        migrations.AddField(
            model_name='departmentuser',
            name='azure_ad_data',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, editable=False, help_text='Cache of Azure AD data', null=True),
        ),
        migrations.AddField(
            model_name='departmentuser',
            name='azure_ad_data_updated',
            field=models.DateTimeField(editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='departmentuser',
            name='account_type',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(2, 'L1 User Account - Permanent'), (3, 'L1 User Account - Agency contract'), (0, 'L1 User Account - Department fixed-term contract'), (8, 'L1 User Account - Seasonal'), (6, 'L1 User Account - Vendor'), (7, 'L1 User Account - Volunteer'), (1, 'L1 User Account - Other/Alumni'), (11, 'L1 User Account - RoomMailbox'), (12, 'L1 User Account - EquipmentMailbox'), (10, 'L2 Service Account - System'), (5, 'L1 Group (shared) Mailbox - Shared account'), (9, 'L1 Role Account - Role-based account'), (4, 'Terminated'), (14, 'Unknown - AD disabled'), (15, 'Cleanup - Permanent'), (16, 'Unknown - AD active')], help_text='Employee network account status', null=True),
        ),
        migrations.AlterField(
            model_name='departmentuser',
            name='ad_guid',
            field=models.CharField(blank=True, help_text='On-premise AD ObjectGUID', max_length=48, null=True, unique=True, verbose_name='AD GUID'),
        ),
        migrations.AlterField(
            model_name='departmentuser',
            name='title',
            field=models.CharField(blank=True, help_text='Occupation position title (should match Ascender position title)', max_length=128, null=True),
        ),
    ]
