# Generated by Django 2.2.24 on 2021-06-29 05:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organisation', '0003_auto_20210618_1207'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='departmentuser',
            name='mail_nickname',
        ),
    ]
