# Generated by Django 4.2.10 on 2024-02-23 02:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("organisation", "0003_delete_orgunit"),
    ]

    operations = [
        migrations.AlterField(
            model_name="departmentuser",
            name="email",
            field=models.EmailField(
                editable=False,
                help_text="Account email address",
                max_length=254,
                unique=True,
            ),
        ),
    ]
