# Generated by Django 5.2.4 on 2025-07-24 01:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("organisation", "0003_departmentuser_last_signin_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="departmentuser",
            name="contractor",
        ),
        migrations.RemoveField(
            model_name="departmentuser",
            name="executive",
        ),
        migrations.RemoveField(
            model_name="departmentuser",
            name="extension",
        ),
        migrations.RemoveField(
            model_name="departmentuser",
            name="home_phone",
        ),
        migrations.RemoveField(
            model_name="departmentuser",
            name="notes",
        ),
        migrations.RemoveField(
            model_name="departmentuser",
            name="other_phone",
        ),
        migrations.RemoveField(
            model_name="departmentuser",
            name="security_clearance",
        ),
        migrations.RemoveField(
            model_name="departmentuser",
            name="shared_account",
        ),
        migrations.RemoveField(
            model_name="departmentuser",
            name="vip",
        ),
        # Manual additions: rename & alter name_update_reference field.
        migrations.RenameField(model_name="departmentuser", old_name="name_update_reference", new_name="update_reference"),
        migrations.AlterField(
            model_name="departmentuser",
            name="update_reference",
            field=models.CharField(blank=True, help_text="Reference(s) for name/CC change request", max_length=512, null=True),
        ),
    ]
