# Generated by Django 5.2.5 on 2025-09-04 02:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organisation', '0004_remove_departmentuser_contractor_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='departmentuser',
            name='last_password_change',
            field=models.DateTimeField(editable=False, help_text='The time when the user account password was last changed', null=True),
        ),
        migrations.AlterField(
            model_name='departmentuser',
            name='account_type',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(2, 'L1 User Account - Permanent'), (0, 'L1 User Account - Contract'), (8, 'L1 User Account - Seasonal'), (6, 'L1 User Account - Vendor/External'), (7, 'L1 User Account - Volunteer'), (1, 'L1 User Account - Alumni/Other'), (14, 'Unknown')], help_text='Employee network account status', null=True),
        ),
        migrations.AlterField(
            model_name='departmentuser',
            name='dir_sync_enabled',
            field=models.BooleanField(default=None, help_text='Entra ID account is synced to on-prem Active Directory', null=True),
        ),
    ]
