# Generated by Django 2.0.6 on 2018-08-16 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organisation', '0004_locations_20180726_1346'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orgunit',
            name='name',
            field=models.CharField(max_length=256),
        ),
    ]
