# Generated by Django 2.2.24 on 2021-07-16 03:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organisation', '0004_remove_departmentuser_mail_nickname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='departmentuser',
            name='cost_centre',
            field=models.ForeignKey(blank=True, help_text='Cost centre to which the employee currently belongs', limit_choices_to={'active': True}, null=True, on_delete=django.db.models.deletion.PROTECT, to='organisation.CostCentre'),
        ),
        migrations.AlterField(
            model_name='departmentuser',
            name='location',
            field=models.ForeignKey(blank=True, help_text='Current physical workplace.', limit_choices_to={'active': True}, null=True, on_delete=django.db.models.deletion.PROTECT, to='organisation.Location'),
        ),
        migrations.AlterField(
            model_name='departmentuser',
            name='manager',
            field=models.ForeignKey(blank=True, help_text='Staff member who manages this employee', limit_choices_to={'active': True}, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='manages', to='organisation.DepartmentUser'),
        ),
        migrations.AlterField(
            model_name='departmentuser',
            name='org_unit',
            field=models.ForeignKey(blank=True, help_text='The organisational unit to which the employee belongs.', limit_choices_to={'active': True}, null=True, on_delete=django.db.models.deletion.PROTECT, to='organisation.OrgUnit', verbose_name='organisational unit'),
        ),
    ]
