# Generated by Django 2.2.24 on 2021-07-20 04:00

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organisation', '0005_auto_20210716_1139'),
    ]

    operations = [
        migrations.CreateModel(
            name='DepartmentUserLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('log', django.contrib.postgres.fields.jsonb.JSONField(default=dict, editable=False)),
                ('department_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organisation.DepartmentUser')),
            ],
        ),
    ]
