# Generated by Django 5.2.6 on 2025-09-30 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organisation', '0005_departmentuser_last_password_change_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='departmentuser',
            name='position_no',
            field=models.CharField(blank=True, help_text="Optional Ascender position number to specify the user's current active job", max_length=128, null=True, unique=True, verbose_name='position no.'),
        ),
    ]
