# Generated by Django 2.2.24 on 2021-09-06 01:10

import django.contrib.postgres.fields
import django.contrib.postgres.fields.citext
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organisation', '0006_departmentuserlog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='departmentuser',
            name='active',
            field=models.BooleanField(default=True, editable=False, help_text='Account is enabled within Active Directory.'),
        ),
        migrations.AlterField(
            model_name='departmentuser',
            name='ad_guid',
            field=models.CharField(blank=True, help_text='On-premise Active Directory unique object ID', max_length=48, null=True, unique=True, verbose_name='AD GUID'),
        ),
        migrations.AlterField(
            model_name='departmentuser',
            name='ascender_data_updated',
            field=models.DateTimeField(editable=False, help_text='Timestamp of when Ascender data was last updated for this user', null=True),
        ),
        migrations.AlterField(
            model_name='departmentuser',
            name='assigned_licences',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=254), blank=True, help_text='Assigned Microsoft 365 licences', null=True, size=None),
        ),
        migrations.AlterField(
            model_name='departmentuser',
            name='azure_guid',
            field=models.CharField(blank=True, editable=False, help_text='Azure Active Directory unique object ID', max_length=48, null=True, unique=True, verbose_name='Azure GUID'),
        ),
        migrations.AlterField(
            model_name='departmentuser',
            name='dir_sync_enabled',
            field=models.NullBooleanField(default=None, help_text='Azure AD account is synced to on-prem AD'),
        ),
        migrations.AlterField(
            model_name='departmentuser',
            name='email',
            field=django.contrib.postgres.fields.citext.CIEmailField(editable=False, help_text='Account email address', max_length=254, unique=True),
        ),
    ]
