# Generated by Django 2.0.6 on 2018-08-29 09:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organisation', '0006_auto_20180829_1733'),
    ]

    operations = [
        migrations.AlterField(
            model_name='costcentre',
            name='org_position',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='organisation.OrgUnit'),
        ),
    ]
