# Generated by Django 5.2.7 on 2025-10-02 02:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organisation', '0006_departmentuser_position_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='departmentuser',
            name='account_type',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(2, 'L1 User Account - Permanent'), (0, 'L1 User Account - Contract'), (8, 'L1 User Account - Seasonal'), (6, 'L1 User Account - Vendor/External'), (7, 'L1 User Account - Volunteer'), (1, 'L1 User Account - Alumni/Other'), (9, 'L1 Role Account - Role-based account'), (14, 'Unknown')], help_text='Employee network account status', null=True),
        ),
    ]
