# Generated by Django 2.2.24 on 2021-10-14 01:55

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organisation', '0007_auto_20210906_0910'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='departmentuser',
            name='position_type',
        ),
        migrations.AlterField(
            model_name='departmentuser',
            name='ad_data',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=dict, editable=False, help_text='Cache of on-premise AD data', null=True),
        ),
        migrations.AlterField(
            model_name='departmentuser',
            name='ascender_data',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=dict, editable=False, help_text='Cache of staff Ascender data', null=True),
        ),
        migrations.AlterField(
            model_name='departmentuser',
            name='azure_ad_data',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=dict, editable=False, help_text='Cache of Azure AD data', null=True),
        ),
        migrations.AlterField(
            model_name='departmentuser',
            name='given_name',
            field=models.CharField(blank=True, help_text='First name', max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='departmentuser',
            name='name',
            field=models.CharField(max_length=128, verbose_name='display name'),
        ),
        migrations.AlterField(
            model_name='departmentuser',
            name='surname',
            field=models.CharField(blank=True, help_text='Last name', max_length=128, null=True),
        ),
    ]
