# Generated by Django 5.2.9 on 2026-01-08 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organisation', '0007_alter_departmentuser_account_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='departmentuser',
            name='azure_ad_data',
            field=models.JSONField(blank=True, default=dict, editable=False, help_text='Cache of Entra ID data', null=True),
        ),
        migrations.AlterField(
            model_name='departmentuser',
            name='position_no',
            field=models.CharField(blank=True, help_text="Optional Ascender position number to specify the user's current active job", max_length=128, null=True, verbose_name='position no.'),
        ),
    ]
