# Generated by Django 2.0.6 on 2018-11-26 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organisation', '0007_auto_20180829_1733'),
    ]

    operations = [
        migrations.AddField(
            model_name='costcentre',
            name='ascender_code',
            field=models.CharField(max_length=16, null=True, unique=True),
        ),
    ]
