# Generated by Django 5.2.14 on 2026-06-23 05:18

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organisation', '0008_alter_departmentuser_azure_ad_data_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='departmentuser',
            name='assigned_groups',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=254), blank=True, help_text="Entra ID groups assigned to this user's account", null=True, size=None),
        ),
    ]
