# Generated by Django 2.2.24 on 2021-10-27 05:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organisation', '0008_auto_20211014_0955'),
    ]

    operations = [
        migrations.AlterField(
            model_name='costcentre',
            name='admin',
            field=models.ForeignKey(blank=True, help_text='Adminstration Officer', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='admin_ccs', to='organisation.DepartmentUser'),
        ),
        migrations.AlterField(
            model_name='costcentre',
            name='business_manager',
            field=models.ForeignKey(blank=True, help_text='Business Manager', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bmanage_ccs', to='organisation.DepartmentUser'),
        ),
        migrations.AlterField(
            model_name='costcentre',
            name='manager',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='manage_ccs', to='organisation.DepartmentUser'),
        ),
        migrations.AlterField(
            model_name='costcentre',
            name='tech_contact',
            field=models.ForeignKey(blank=True, help_text='Technical Contact', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tech_ccs', to='organisation.DepartmentUser'),
        ),
        migrations.AlterField(
            model_name='departmentuser',
            name='manager',
            field=models.ForeignKey(blank=True, help_text='Staff member who manages this employee', limit_choices_to={'active': True}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='manages', to='organisation.DepartmentUser'),
        ),
        migrations.AlterField(
            model_name='location',
            name='manager',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='location_manager', to='organisation.DepartmentUser'),
        ),
        migrations.AlterField(
            model_name='orgunit',
            name='manager',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='organisation.DepartmentUser'),
        ),
    ]
