# Generated by Django 2.1.5 on 2019-01-23 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organisation', '0008_costcentre_ascender_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='ascender_code',
            field=models.CharField(max_length=16, null=True, unique=True),
        ),
    ]
