# Generated by Django 2.2.24 on 2021-12-05 23:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organisation', '0009_auto_20211027_1341'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='location',
            name='bandwidth_url',
        ),
        migrations.RemoveField(
            model_name='location',
            name='email',
        ),
        migrations.RemoveField(
            model_name='location',
            name='manager',
        ),
        migrations.RemoveField(
            model_name='location',
            name='url',
        ),
    ]
