# Generated by Django 2.1.5 on 2019-02-12 01:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organisation', '0009_location_ascender_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='costcentre',
            name='ascender_code',
            field=models.CharField(blank=True, max_length=16, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='location',
            name='ascender_code',
            field=models.CharField(blank=True, max_length=16, null=True, unique=True),
        ),
    ]
