# Generated by Django 2.1.7 on 2019-05-07 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organisation', '0010_auto_20190212_0913'),
    ]

    operations = [
        migrations.AddField(
            model_name='departmentuser',
            name='date_hr_term',
            field=models.DateTimeField(blank=True, editable=False, verbose_name='HR termination date', help_text='Date on file with HR as the job termination date.', null=True),
        ),
        migrations.AddField(
            model_name='departmentuser',
            name='hr_auto_expiry',
            field=models.BooleanField(default=False, help_text='When the HR termination date changes, automatically update the expiry date to match.', verbose_name='HR auto expiry'),
        ),
        migrations.AlterField(
            model_name='departmentuser',
            name='expiry_date',
            field=models.DateTimeField(blank=True, help_text='Date that the AD account will expire.', null=True),
        ),
    ]
