# Generated by Django 2.1.11 on 2019-09-03 02:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organisation', '0011_auto_20190507_1619'),
    ]

    operations = [
        migrations.AlterField(
            model_name='departmentuser',
            name='level',
            field=models.PositiveIntegerField(editable=False),
        ),
        migrations.AlterField(
            model_name='departmentuser',
            name='lft',
            field=models.PositiveIntegerField(editable=False),
        ),
        migrations.AlterField(
            model_name='departmentuser',
            name='rght',
            field=models.PositiveIntegerField(editable=False),
        ),
        migrations.AlterField(
            model_name='orgunit',
            name='level',
            field=models.PositiveIntegerField(editable=False),
        ),
        migrations.AlterField(
            model_name='orgunit',
            name='lft',
            field=models.PositiveIntegerField(editable=False),
        ),
        migrations.AlterField(
            model_name='orgunit',
            name='rght',
            field=models.PositiveIntegerField(editable=False),
        ),
    ]
