# Generated by Django 5.2.17 on 2026-09-09 09:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organisation', '0011_remove_departmentuser_assigned_entra_group_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='departmentuser',
            name='assigned_groups',
        ),
    ]
