# Generated by Django 2.2.27 on 2022-03-08 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organisation', '0011_auto_20220303_1059'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='ascender_desc',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
