# Generated by Django 2.2.27 on 2022-03-31 04:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organisation', '0012_location_ascender_desc'),
    ]

    operations = [
        migrations.AddField(
            model_name='orgunit',
            name='ascender_code',
            field=models.CharField(blank=True, max_length=16, null=True, unique=True),
        ),
    ]
