# Generated by Django 2.2.14 on 2020-07-31 02:41

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organisation', '0012_auto_20190903_1039'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='departmentuser',
            name='ad_data',
        ),
        migrations.RemoveField(
            model_name='departmentuser',
            name='ad_deleted',
        ),
        migrations.RemoveField(
            model_name='departmentuser',
            name='ad_dn',
        ),
        migrations.RemoveField(
            model_name='departmentuser',
            name='date_ad_updated',
        ),
        migrations.RemoveField(
            model_name='departmentuser',
            name='in_sync',
        ),
        migrations.RemoveField(
            model_name='departmentuser',
            name='photo',
        ),
        migrations.RemoveField(
            model_name='departmentuser',
            name='photo_ad',
        ),
        migrations.RemoveField(
            model_name='departmentuser',
            name='populate_primary_group',
        ),
        migrations.RemoveField(
            model_name='departmentuser',
            name='sso_roles',
        ),
        migrations.AddField(
            model_name='costcentre',
            name='division_name',
            field=models.CharField(blank=True, choices=[('BCS', 'DBCA Biodiversity and Conservation Science'), ('BGPA', 'Botanic Gardens and Parks Authority'), ('CBS', 'DBCA Corporate and Business Services'), ('CPC', 'Conservation and Parks Commission'), ('ODG', 'Office of the Director General'), ('PWS', 'Parks and Wildlife Service'), ('RIA', 'Rottnest Island Authority'), ('ZPA', 'Zoological Parks Authority')], max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='departmentuser',
            name='dir_syn_enabled',
            field=models.NullBooleanField(default=None),
        ),
        migrations.AddField(
            model_name='departmentuser',
            name='mail_nickname',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='departmentuser',
            name='manager',
            field=models.ForeignKey(blank=True, help_text='Staff member who manages this employee', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='manages', to='organisation.DepartmentUser'),
        ),
        migrations.AddField(
            model_name='departmentuser',
            name='proxy_addresses',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=254), blank=True, help_text='Email aliases', null=True, size=None),
        ),
        migrations.AlterField(
            model_name='departmentuser',
            name='account_type',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(2, 'L1 User Account - Permanent'), (3, 'L1 User Account - Agency contract'), (0, 'L1 User Account - Department fixed-term contract'), (8, 'L1 User Account - Seasonal'), (6, 'L1 User Account - Vendor'), (7, 'L1 User Account - Volunteer'), (1, 'L1 User Account - Other/Alumni'), (11, 'L1 User Account - RoomMailbox'), (12, 'L1 User Account - EquipmentMailbox'), (10, 'L2 Service Account - System'), (5, 'L1 Group (shared) Mailbox - Shared account'), (9, 'L1 Role Account - Role-based account'), (4, 'Terminated'), (14, 'Unknown - AD disabled'), (15, 'Cleanup - Permanent'), (16, 'Unknown - AD active')], help_text='Employee network account status (should match Alesco status)', null=True),
        ),
        migrations.AlterField(
            model_name='departmentuser',
            name='active',
            field=models.BooleanField(default=True, editable=False, help_text='Account is enabled/disabled within Active Directory.'),
        ),
        migrations.AlterField(
            model_name='departmentuser',
            name='azure_guid',
            field=models.CharField(blank=True, editable=False, help_text='Azure AD ObjectId', max_length=48, null=True, unique=True, verbose_name='Azure GUID'),
        ),
        migrations.AlterField(
            model_name='departmentuser',
            name='cost_centre',
            field=models.ForeignKey(blank=True, help_text='Cost centre to which the employee currently belongs', null=True, on_delete=django.db.models.deletion.PROTECT, to='organisation.CostCentre'),
        ),
        migrations.AlterField(
            model_name='departmentuser',
            name='email',
            field=models.EmailField(editable=False, help_text='Account primary email address', max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='departmentuser',
            name='given_name',
            field=models.CharField(blank=True, help_text='Legal first name (matches birth certificate/passport/etc.)', max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='departmentuser',
            name='location',
            field=models.ForeignKey(blank=True, help_text='Current physical workplace.', null=True, on_delete=django.db.models.deletion.PROTECT, to='organisation.Location'),
        ),
        migrations.AlterField(
            model_name='departmentuser',
            name='mobile_phone',
            field=models.CharField(blank=True, help_text='Work mobile number', max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='departmentuser',
            name='name',
            field=models.CharField(help_text='Format: [Given name] [Surname]', max_length=128, verbose_name='display name'),
        ),
        migrations.AlterField(
            model_name='departmentuser',
            name='surname',
            field=models.CharField(blank=True, help_text='Legal surname (matches birth certificate/passport/etc.)', max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='departmentuser',
            name='telephone',
            field=models.CharField(blank=True, help_text='Work telephone number', max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='departmentuser',
            name='title',
            field=models.CharField(blank=True, help_text='Occupation position title (should match Alesco)', max_length=128, null=True),
        ),
    ]
