# Generated by Django 5.2.17 on 2026-09-15 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organisation', '0012_remove_departmentuser_assigned_groups'),
    ]

    operations = [
        migrations.AddField(
            model_name='departmentuser',
            name='term_date_data',
            field=models.JSONField(blank=True, default=list, editable=False, help_text='Cache of staff Ascender termination date data. May include 1 or more records if the user has/ had multiple jobs with the department.', null=True),
        ),
    ]
