# Generated by Django 3.2.12 on 2022-03-31 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organisation', '0013_orgunit_ascender_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='departmentuser',
            name='ad_data',
            field=models.JSONField(blank=True, default=dict, editable=False, help_text='Cache of on-premise AD data', null=True),
        ),
        migrations.AlterField(
            model_name='departmentuser',
            name='ascender_data',
            field=models.JSONField(blank=True, default=dict, editable=False, help_text='Cache of staff Ascender data', null=True),
        ),
        migrations.AlterField(
            model_name='departmentuser',
            name='azure_ad_data',
            field=models.JSONField(blank=True, default=dict, editable=False, help_text='Cache of Azure AD data', null=True),
        ),
        migrations.AlterField(
            model_name='departmentuser',
            name='dir_sync_enabled',
            field=models.BooleanField(default=None, help_text='Azure AD account is synced to on-prem AD', null=True),
        ),
        migrations.AlterField(
            model_name='departmentuserlog',
            name='log',
            field=models.JSONField(default=dict, editable=False),
        ),
    ]
