# Generated by Django 2.2.14 on 2020-08-04 03:32

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organisation', '0013_auto_20200731_1041'),
    ]

    operations = [
        migrations.RenameField(
            model_name='departmentuser',
            old_name='dir_syn_enabled',
            new_name='dir_sync_enabled',
        ),
        migrations.AddField(
            model_name='departmentuser',
            name='assigned_licences',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=254), blank=True, help_text='Assigned Office 365 licences', null=True, size=None),
        ),
    ]
