# Generated by Django 3.2.13 on 2022-05-02 01:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organisation', '0014_auto_20220331_1447'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orgunit',
            name='ascender_code',
        ),
        migrations.AddField(
            model_name='orgunit',
            name='ascender_clevel',
            field=models.CharField(blank=True, max_length=128, null=True, unique=True),
        ),
    ]
