# Generated by Django 3.2.13 on 2022-05-03 05:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organisation', '0015_auto_20220502_0911'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ADAction',
        ),
    ]
