# Generated by Django 3.2.13 on 2022-06-28 03:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organisation', '0016_delete_adaction'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='costcentre',
            name='admin',
        ),
        migrations.RemoveField(
            model_name='costcentre',
            name='business_manager',
        ),
        migrations.RemoveField(
            model_name='costcentre',
            name='org_position',
        ),
        migrations.RemoveField(
            model_name='costcentre',
            name='tech_contact',
        ),
    ]
