# Generated by Django 2.2.16 on 2020-09-16 02:56

import django.contrib.postgres.fields.citext
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organisation', '0017_remove_costcentre_division'),
    ]

    operations = [
        migrations.AlterField(
            model_name='departmentuser',
            name='email',
            field=django.contrib.postgres.fields.citext.CIEmailField(editable=False, help_text='Account primary email address', max_length=254, unique=True),
        ),
    ]
