# Generated by Django 3.2.15 on 2022-09-07 02:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organisation', '0017_auto_20220628_1123'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='address',
            field=models.TextField(blank=True),
        ),
    ]
