# Generated by Django 3.2.16 on 2022-11-14 03:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organisation', '0018_alter_location_address'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='departmentuser',
            name='org_unit',
        ),
    ]
