# Generated by Django 3.2.16 on 2022-11-24 05:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organisation', '0019_remove_departmentuser_org_unit'),
    ]

    operations = [
        migrations.DeleteModel(
            name='OrgUnit',
        ),
    ]
