# Generated by Django 3.2.17 on 2023-02-15 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organisation', '0019_remove_departmentuser_org_unit'),
    ]

    operations = [
        migrations.CreateModel(
            name='AscenderActionLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('level', models.CharField(choices=[('INFO', 'INFO'), ('WARNING', 'WARNING'), ('ERROR', 'ERROR')], max_length=64)),
                ('log', models.CharField(max_length=512)),
            ],
            options={
                'ordering': ('-created',),
            },
        ),
    ]
