# Generated by Django 3.2.17 on 2023-02-22 01:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organisation', '0020_ascenderactionlog'),
    ]

    operations = [
        migrations.AddField(
            model_name='ascenderactionlog',
            name='ascender_data',
            field=models.JSONField(blank=True, default=dict, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='ascenderactionlog',
            name='level',
            field=models.CharField(choices=[('INFO', 'INFO'), ('WARNING', 'WARNING'), ('ERROR', 'ERROR')], editable=False, max_length=64),
        ),
        migrations.AlterField(
            model_name='ascenderactionlog',
            name='log',
            field=models.CharField(editable=False, max_length=512),
        ),
    ]
