# Generated by Django 2.2.16 on 2020-11-04 04:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organisation', '0020_auto_20201021_1352'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orgunit',
            name='ad_dn',
        ),
        migrations.RemoveField(
            model_name='orgunit',
            name='ad_guid',
        ),
        migrations.RemoveField(
            model_name='orgunit',
            name='sync_o365',
        ),
        migrations.AddField(
            model_name='orgunit',
            name='division_unit',
            field=models.ForeignKey(blank=True, help_text='Division-level unit to which this unit belongs', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='division_orgunits', to='organisation.OrgUnit'),
        ),
    ]
