# Generated by Django 3.2.20 on 2023-08-10 02:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organisation', '0021_auto_20230222_0902'),
    ]

    operations = [
        migrations.AddField(
            model_name='departmentuser',
            name='maiden_name',
            field=models.CharField(blank=True, help_text='Optional maiden name value, for the purposes of setting Display Name within Azure AD', max_length=128, null=True),
        ),
    ]
