# Generated by Django 2.2.16 on 2020-11-09 02:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organisation', '0022_auto_20201109_1007'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orgunit',
            name='details',
        ),
    ]
