# Generated by Django 2.2.16 on 2020-12-02 03:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organisation', '0023_remove_orgunit_details'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='departmentuser',
            name='cost_centres_secondary',
        ),
        migrations.RemoveField(
            model_name='departmentuser',
            name='date_hr_term',
        ),
        migrations.RemoveField(
            model_name='departmentuser',
            name='extra_data',
        ),
        migrations.RemoveField(
            model_name='departmentuser',
            name='hr_auto_expiry',
        ),
        migrations.RemoveField(
            model_name='departmentuser',
            name='o365_licence',
        ),
        migrations.RemoveField(
            model_name='departmentuser',
            name='org_data',
        ),
        migrations.RemoveField(
            model_name='departmentuser',
            name='org_units_secondary',
        ),
        migrations.RemoveField(
            model_name='departmentuser',
            name='secondary_locations',
        ),
        migrations.AlterField(
            model_name='departmentuser',
            name='employee_id',
            field=models.CharField(blank=True, help_text='Ascender employee number', max_length=128, null=True, unique=True, verbose_name='Employee ID'),
        ),
        migrations.AlterField(
            model_name='departmentuser',
            name='position_type',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(0, 'Full time'), (1, 'Part time'), (2, 'Casual'), (3, 'Other')], default=0, help_text='Employee position working arrangement (Ascender employment status)', null=True),
        ),
        migrations.AlterField(
            model_name='departmentuser',
            name='preferred_name',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
