# Generated by Django 2.2.16 on 2020-12-03 02:18

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organisation', '0025_auto_20201202_1351'),
    ]

    operations = [
        migrations.AlterField(
            model_name='departmentuser',
            name='ascender_data',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, editable=False, help_text='Cache of staff Ascender data', null=True),
        ),
        migrations.AlterField(
            model_name='departmentuser',
            name='ascender_data_updated',
            field=models.DateTimeField(editable=False, null=True),
        ),
    ]
