# Generated by Django 2.2.16 on 2020-12-07 01:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organisation', '0026_auto_20201203_1018'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='departmentuser',
            name='expiry_date',
        ),
    ]
