# Generated by Django 2.2.16 on 2021-01-15 03:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organisation', '0027_remove_departmentuser_expiry_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='costcentre',
            name='name',
        ),
    ]
