apiVersion: batch/v1
kind: CronJob
metadata:
  name: itassets-cronjob
spec:
  # AWST: 12:00, Mon-Fri
  schedule: '0 4 * * 1-5'
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: itassets-cronjob
              args: ['manage.py', 'department_users_changes_report', '--emails', 'kmsupport@dbca.wa.gov.au']
              envFrom:
                - secretRef:
                    name: itassets-env-prod
