apiVersion: batch/v1
kind: CronJob
metadata:
  name: itassets-cronjob
spec:
  # AWST: 20/50 min past the hour, 08:00-19:00, Mon-Fri
  schedule: '20,50 0-10 * * 1-5'
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: itassets-cronjob
              args: ['manage.py', 'check_onprem_accounts', '--container', 'azuread', '--path', 'adusers.json']
              envFrom:
                - secretRef:
                    name: itassets-env-prod
