# Generated by Django 2.2.10 on 2020-06-02 00:06

import django.contrib.postgres.fields
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('registers', '0027_changerequest_post_complete_email_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Domain',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, unique=True)),
                ('level', models.PositiveSmallIntegerField(editable=False)),
                ('score', models.BigIntegerField(editable=False, unique=True)),
                ('desc', models.TextField(blank=True, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('parent', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='children', to='nginx.Domain')),
            ],
        ),
        migrations.CreateModel(
            name='SystemAlias',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, unique=True)),
                ('desc', models.TextField(blank=True, null=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('system', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='alias', to='registers.ITSystem')),
            ],
        ),
        migrations.CreateModel(
            name='SystemEnv',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, unique=True)),
                ('desc', models.TextField(blank=True, null=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='WebApp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(editable=False, max_length=128, unique=True)),
                ('redirect_to_other', models.CharField(editable=False, max_length=128, null=True)),
                ('redirect_path', models.CharField(editable=False, max_length=128, null=True)),
                ('original_configs', django.contrib.postgres.fields.jsonb.JSONField(editable=False, null=True)),
                ('configure_txt', models.TextField(editable=False)),
                ('auth_domain', models.PositiveSmallIntegerField(choices=[(11, 'DBCA'), (12, 'DPAW'), (13, 'UAT'), (0, '-')], editable=False)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('config_modified', models.DateTimeField(editable=False, null=True)),
                ('config_changed_columns', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=128), editable=False, null=True, size=None)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('domain', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='webapps', to='nginx.Domain')),
                ('redirect_to', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='redirect_from', to='nginx.WebApp')),
                ('system_alias', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='webapps', to='nginx.SystemAlias')),
                ('system_env', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='webapps', to='nginx.SystemEnv')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='WebAppLocation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(editable=False, max_length=256)),
                ('location_type', models.PositiveSmallIntegerField(choices=[(1, 'Exact Location'), (2, 'Prefix Location'), (3, 'Case Sensitive Regex Location'), (4, 'Case Insensitive Regex Location'), (5, 'Non-regex Location')], editable=False)),
                ('auth_type', models.PositiveSmallIntegerField(choices=[(0, 'SSO Not Required'), (1, 'SSO Required'), (2, 'SSO Dual Auth Required'), (11, 'SSO To DBCA'), (12, 'SSO To DPAW'), (13, 'SSO To UAT')])),
                ('cors_enabled', models.BooleanField(default=False, editable=False)),
                ('forward_protocol', models.PositiveSmallIntegerField(choices=[(1, 'Http'), (2, 'Https'), (3, 'Uwsgi')], editable=False, null=True)),
                ('forward_path', models.CharField(editable=False, max_length=256, null=True)),
                ('redirect', models.CharField(editable=False, max_length=256, null=True)),
                ('return_code', models.PositiveSmallIntegerField(editable=False, null=True)),
                ('refuse', models.BooleanField(default=False, editable=False)),
                ('original_configs', django.contrib.postgres.fields.jsonb.JSONField(editable=False, null=True)),
                ('configure_txt', models.TextField(editable=False)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('config_modified', models.DateTimeField(editable=False, null=True)),
                ('config_changed_columns', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=128), editable=False, null=True, size=None)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('app', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='locations', to='nginx.WebApp')),
            ],
            options={
                'unique_together': {('app', 'location_type', 'location')},
            },
        ),
        migrations.CreateModel(
            name='WebServer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, unique=True)),
                ('category', models.PositiveSmallIntegerField(choices=[(1, 'AWS Server'), (2, 'Rancher Cluster'), (4, 'Docker Server'), (3, 'Web Server')], null=True)),
                ('desc', models.TextField(blank=True, null=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='WebAppLocationServer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('port', models.PositiveIntegerField()),
                ('user_added', models.BooleanField(default=True, editable=False)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('location', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='servers', to='nginx.WebAppLocation')),
                ('server', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='nginx.WebServer')),
            ],
            options={
                'unique_together': {('location', 'server', 'port')},
            },
        ),
        migrations.CreateModel(
            name='WebAppListen',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('listen_host', models.CharField(editable=False, max_length=128)),
                ('listen_port', models.PositiveIntegerField(editable=False)),
                ('https', models.BooleanField(default=False, editable=False)),
                ('configure_txt', models.CharField(editable=False, max_length=256)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('config_modified', models.DateTimeField(editable=False, null=True)),
                ('config_changed_columns', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=128), editable=False, null=True, size=None)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('app', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='listens', to='nginx.WebApp')),
            ],
            options={
                'unique_together': {('app', 'listen_host', 'listen_port')},
            },
        ),
    ]
