# Generated by Django 3.2.12 on 2022-04-07 02:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nginx', '0001_squashed_0013_remove_webserver_host'),
    ]

    operations = [
        migrations.AlterField(
            model_name='webapp',
            name='original_configs',
            field=models.JSONField(editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='webapplocation',
            name='original_configs',
            field=models.JSONField(editable=False, null=True),
        ),
    ]
