# Generated by Django 2.2.10 on 2020-06-26 06:15

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rancher', '0001_initial'),
        ('nginx', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='webapplocationserver',
            name='rancher_workload',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='servers', to='rancher.Workload'),
        ),
        migrations.AddField(
            model_name='webserver',
            name='other_names',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=128), editable=False, null=True, size=None),
        ),
    ]
