# Generated by Django 2.2.14 on 2020-08-13 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nginx', '0005_auto_20200810_1038'),
    ]

    operations = [
        migrations.AddField(
            model_name='webapp',
            name='clientip_subnet',
            field=models.CharField(editable=False, max_length=64, null=True, verbose_name='users'),
        ),
    ]
