# Generated by Django 2.2.14 on 2020-08-13 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nginx', '0006_webapp_clientip_subnet'),
    ]

    operations = [
        migrations.AddField(
            model_name='webappaccessdailyreport',
            name='client_closed_requests',
            field=models.PositiveIntegerField(default=0, editable=False),
        ),
    ]
