# Generated by Django 2.2.14 on 2020-08-18 01:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nginx', '0007_webappaccessdailyreport_client_closed_requests'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requestpathnormalizer',
            name='normalize_code',
            field=models.TextField(help_text="The source code of the module which contains a method 'def normalize(request_path)' to return a normalized request  path"),
        ),
    ]
