# Generated by Django 2.2.14 on 2020-08-20 06:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nginx', '0008_auto_20200818_0944'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='systemalias',
            options={'verbose_name_plural': 'system aliases'},
        ),
        migrations.AlterModelOptions(
            name='webappaccessdailyreport',
            options={'get_latest_by': 'log_day'},
        ),
    ]
