# Generated by Django 2.2.16 on 2020-10-08 03:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nginx', '0009_auto_20200820_1424'),
    ]

    operations = [
        migrations.AlterIndexTogether(
            name='webappaccesslog',
            index_together={('log_starttime', 'webapp', 'webapplocation'), ('webapp', 'webapplocation'), ('webapp', 'http_status')},
        ),
    ]
