# Generated by Django 2.2.21 on 2021-05-09 23:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nginx', '0011_auto_20201008_1119'),
    ]

    operations = [
        migrations.AlterIndexTogether(
            name='webappaccessdailylog',
            index_together={('webserver', 'request_path'), ('log_day', 'webapp', 'webapplocation'), ('webapp', 'webapplocation')},
        ),
    ]
