# Generated by Django 2.2.27 on 2022-02-21 05:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nginx', '0012_auto_20210510_0751'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='webserver',
            name='host',
        ),
    ]
