# Generated by Django 2.2.14 on 2020-07-09 03:34

import bigpicture.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dependency',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('object_id', models.PositiveIntegerField(help_text='The primary key of the target object.')),
                ('type', models.CharField(choices=[('Service', 'Service'), ('Compute', 'Compute'), ('Storage', 'Storage'), ('Proxy', 'Proxy')], help_text='The type/category of this dependency.', max_length=64)),
                ('health', models.CharField(blank=True, choices=[('Recommended', 'Recommended'), ('Supported', 'Supported'), ('Constrained', 'Constrained'), ('High risk', 'High risk')], help_text='A point-in-time assessment of the health of this dependency.', max_length=64, null=True)),
                ('content_type', models.ForeignKey(help_text='The type of the target object.', limit_choices_to=bigpicture.models.limit_dependency_content_type_choices, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType')),
            ],
            options={
                'verbose_name_plural': 'dependencies',
            },
        ),
        migrations.CreateModel(
            name='Platform',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(help_text='A unique name for this platform.', max_length=256, unique=True)),
                ('tier', models.CharField(choices=[('IaaS', 'IaaS'), ('PaaS', 'PaaS'), ('SaaS', 'SaaS'), ('Standalone', 'Standalone')], help_text='The platform tier.', max_length=64)),
                ('health', models.CharField(choices=[('Recommended', 'Recommended'), ('Supported', 'Supported'), ('Constrained', 'Constrained'), ('High risk', 'High risk')], help_text='A point-in-time assessment of the health of this platform dependency.', max_length=64)),
                ('dependencies', models.ManyToManyField(blank=True, help_text='Dependencies that make up this platform.', to='bigpicture.Dependency')),
            ],
        ),
        migrations.CreateModel(
            name='RiskAssessment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('object_id', models.PositiveIntegerField(help_text='The primary key of the target object.')),
                ('category', models.CharField(choices=[('Traffic', 'Traffic'), ('Access', 'Access'), ('Backups', 'Backups'), ('Support', 'Support'), ('Operating System', 'Operating System'), ('Vulnerability', 'Vulnerability'), ('Patching', 'Patching'), ('Contingency plan', 'Contingency plan')], help_text='The category which this risk falls into.', max_length=64)),
                ('rating', models.PositiveIntegerField(help_text='An arbitrary number rating for the risk (higher equals greater risk).')),
                ('notes', models.TextField(blank=True, help_text='Supporting evidence and/or context for this risk assessment.')),
                ('content_type', models.ForeignKey(help_text='The type of the target object.', limit_choices_to=bigpicture.models.limit_dependency_content_type_choices, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType')),
            ],
            options={
                'unique_together': {('category', 'content_type', 'object_id')},
            },
        ),
    ]
