# Generated by Django 2.2.14 on 2020-07-09 04:24

import bigpicture.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bigpicture', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='riskassessment',
            name='content_type',
            field=models.ForeignKey(help_text='The type of the target object.', limit_choices_to=bigpicture.models.limit_risk_assessment_content_type_choices, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType'),
        ),
    ]
