# Generated by Django 2.2.14 on 2020-07-20 01:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bigpicture', '0002_auto_20200709_1224'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dependency',
            old_name='type',
            new_name='category',
        ),
    ]
