# Generated by Django 2.2.14 on 2020-07-22 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bigpicture', '0003_auto_20200720_0904'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dependency',
            name='category',
            field=models.CharField(choices=[('Service', 'Service'), ('Compute', 'Compute'), ('Storage', 'Storage'), ('Proxy', 'Proxy')], help_text='The category of this dependency.', max_length=64),
        ),
    ]
