# Generated by Django 2.2.14 on 2020-08-06 01:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bigpicture', '0005_auto_20200806_0834'),
        ('bigpicture', '0005_auto_20200727_0926'),
    ]

    operations = [
    ]
