# Generated by Django 2.2.14 on 2020-08-19 02:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('bigpicture', '0006_merge_20200806_0944'),
    ]

    operations = [
        migrations.AddField(
            model_name='dependency',
            name='name',
            field=models.TextField(blank=True, editable=False, help_text='String representation value of the content object, for querying'),
        ),
        migrations.AlterUniqueTogether(
            name='dependency',
            unique_together={('content_type', 'object_id', 'category')},
        ),
    ]
