# Generated by Django 2.2.16 on 2021-01-22 04:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bigpicture', '0007_auto_20200819_1037'),
    ]

    operations = [
        migrations.AlterField(
            model_name='riskassessment',
            name='category',
            field=models.CharField(choices=[('Infrastructure location', 'Infrastructure location'), ('Critical function', 'Critical function'), ('Traffic', 'Traffic'), ('Access', 'Access'), ('Backups', 'Backups'), ('Support', 'Support'), ('Operating System', 'Operating System'), ('Vulnerability', 'Vulnerability'), ('Contingency plan', 'Contingency plan')], help_text='The category which this risk falls into.', max_length=64),
        ),
    ]
