# Generated by Django 2.2.24 on 2021-10-20 01:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bigpicture', '0008_auto_20210122_1218'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dependency',
            name='category',
            field=models.CharField(choices=[('Workload', 'Workload'), ('Service', 'Service'), ('Compute', 'Compute'), ('Storage', 'Storage'), ('Proxy target', 'Proxy target')], help_text='The category of this dependency.', max_length=64),
        ),
    ]
