# Generated by Django 2.0.4 on 2018-05-14 02:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0002_auto_20180510_1551'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hardwaremodel',
            name='model_type',
            field=models.CharField(choices=[('Air conditioner', 'Air conditioner'), ('Camera - Compact', 'Camera - Compact'), ('Camera - Conference', 'Camera - Conference'), ('Camera - Security (IP)', 'Camera - Security (IP)'), ('Camera - Other', 'Camera - Other'), ('Cellular repeater', 'Cellular repeater'), ('Computer - Desktop', 'Computer - Desktop'), ('Computer - Laptop', 'Computer - Laptop'), ('Computer - Monitor', 'Computer - Monitor'), ('Computer - Peripheral', 'Computer - Peripheral'), ('Computer - Tablet PC', 'Computer - Tablet PC'), ('Computer - Other', 'Computer - Other'), ('Environmental monitor', 'Environmental monitor'), ('Network - Media converter', 'Network - Media converter'), ('Network - Modem', 'Network - Modem'), ('Network - Module or card', 'Network - Module or card'), ('Network - Music On Hold', 'Network - Music On Hold'), ('Network - Power injector', 'Network - Power injector'), ('Network - Router', 'Network - Router'), ('Network - Switch (Ethernet)', 'Network - Switch (Ethernet)'), ('Network - Switch (FC)', 'Network - Switch (FC)'), ('Network - Wireless AP', 'Network - Wireless AP'), ('Network - Wireless bridge', 'Network - Wireless bridge'), ('Network - Wireless controller', 'Network - Wireless controller'), ('Network - Other', 'Network - Other'), ('Office Equipment - Other', 'Office Equipment - Other'), ('Phone - Conference', 'Phone - Conference'), ('Phone - Desk', 'Phone - Desk'), ('Phone - Gateway', 'Phone - Gateway'), ('Phone - Mobile', 'Phone - Mobile'), ('Phone - Wireless or portable', 'Phone - Wireless or portable'), ('Phone - Other', 'Phone - Other'), ('Power Distribution Unit', 'Power Distribution Unit'), ('Printer - Multifunction copier', 'Printer - Multifunction copier'), ('Printer - Plotter', 'Printer - Plotter'), ('Printer - Server', 'Printer - Server'), ('Printer - Workgroup', 'Printer - Workgroup'), ('Projector', 'Projector'), ('Rack', 'Rack'), ('Server - Blade', 'Server - Blade'), ('Server - Rackmount', 'Server - Rackmount'), ('Server - Tower', 'Server - Tower'), ('Storage - Disk array', 'Storage - Disk array'), ('Storage - Hard Drive', 'Storage - Hard Drive'), ('Storage - NAS', 'Storage - NAS'), ('Storage - SAN', 'Storage - SAN'), ('Storage - Other', 'Storage - Other'), ('Speaker', 'Speaker'), ('Tape autoloader', 'Tape autoloader'), ('Tape drive', 'Tape drive'), ('Telecom - Testing Device', 'Telecom - Testing Device'), ('UPS', 'UPS'), ('Other', 'Other')], help_text='The broad category of this hardware model.', max_length=50),
        ),
    ]
