# Generated by Django 2.0.6 on 2018-08-10 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0003_auto_20180514_1056'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hardwareasset',
            name='status',
            field=models.CharField(choices=[('In storage', 'In storage'), ('Deployed', 'Deployed'), ('Disposed', 'Disposed'), ('Transferred', 'Transferred')], default='In storage', max_length=50),
        ),
    ]
