# Generated by Django 2.2.14 on 2020-09-04 07:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0005_auto_20200706_1209'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hardwareasset',
            name='assigned_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='organisation.DepartmentUser'),
        ),
    ]
