apiVersion: batch/v1
kind: CronJob
metadata:
  name: itassets-cronjob
spec:
  # AWST: 10/40 min past the hour, 07:00-19:00, Mon-Fri
  schedule: '10,40 0-10,23 * * 1-5'
  suspend: true # Remove after new cluster is whitelisted.
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: itassets-cronjob
              args: ['manage.py', 'check_ascender_accounts']
              envFrom:
                - secretRef:
                    name: itassets-env-prod
