# Generated by Django 5.2.12 on 2026-05-26 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itsystems', '0015_alter_itsystemrecord_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itsystemrecord',
            name='link',
            field=models.URLField(blank=True, help_text='URL to web application', max_length=2048, null=True, verbose_name='Link'),
        ),
    ]
