# Generated by Django 5.2.12 on 2026-05-15 02:38

import itsystems.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itsystems', '0015_alter_itsystemrecord_description_and_more'),
        ('organisation', '0008_alter_departmentuser_azure_ad_data_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itsystemrecord',
            name='business_service_owner',
            field=models.ForeignKey(blank=True, help_text='IT system business service owner', null=True, on_delete=itsystems.models.SET_NULL_AND_NOTIFY, related_name='systems_business_service_owner_of', to='organisation.departmentuser', verbose_name='Business Service Owner'),
        ),
        migrations.AlterField(
            model_name='itsystemrecord',
            name='information_custodian',
            field=models.ForeignKey(blank=True, help_text='IT system information custodian', null=True, on_delete=itsystems.models.SET_NULL_AND_NOTIFY, related_name='systems_information_custodian_of', to='organisation.departmentuser', verbose_name='Information Custodian'),
        ),
        migrations.AlterField(
            model_name='itsystemrecord',
            name='system_owner',
            field=models.ForeignKey(blank=True, help_text='IT system owner', null=True, on_delete=itsystems.models.SET_NULL_AND_NOTIFY, related_name='systems_owner_of', to='organisation.departmentuser', verbose_name='System Owner'),
        ),
        migrations.AlterField(
            model_name='itsystemrecord',
            name='technology_custodian',
            field=models.ForeignKey(blank=True, help_text='IT system technology custodian', null=True, on_delete=itsystems.models.SET_NULL_AND_NOTIFY, related_name='systems_technology_custodian_of', to='organisation.departmentuser', verbose_name='Technology Custodian'),
        ),
    ]
