# Generated by Django 5.2.14 on 2026-06-23 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itsystems', '0016_alter_itsystemrecord_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itsystemrecord',
            name='vital_records',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='Vital Records'),
        ),
    ]
