# Generated by Django 5.2.14 on 2026-06-23 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itsystems', '0017_alter_itsystemrecord_vital_records'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itsystemrecord',
            name='disposal_authority',
            field=models.CharField(blank=True, default=None, max_length=255, null=True, verbose_name='Disposal Authority'),
        ),
    ]
