# Generated by Django 5.2.14 on 2026-06-24 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itsystems', '0018_alter_itsystemrecord_disposal_authority'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itsystemrecord',
            name='disposal_authority',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Disposal Authority'),
        ),
    ]
