# Generated by Django 2.0.6 on 2018-07-06 05:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webconfig', '0002_auto_20180503_1006'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='auth_level',
            field=models.SmallIntegerField(choices=[(1, 'SSO'), (2, 'SSO or Basic Auth'), (3, 'Public (SSO Dual)'), (4, 'Subnets (SSO Dual)')], default=1),
        ),
        migrations.AlterField(
            model_name='location',
            name='site',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='locations', to='webconfig.Site'),
        ),
    ]
