# Generated by Django 2.2.10 on 2020-06-30 02:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rancher', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cluster',
            name='refreshed',
            field=models.DateTimeField(editable=False, null=True),
        ),
    ]
