# Generated by Django 2.2.10 on 2020-07-01 07:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rancher', '0002_cluster_refreshed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='database',
            name='server',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='databases', to='rancher.DatabaseServer'),
        ),
        migrations.AlterField(
            model_name='databaseuser',
            name='server',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='users', to='rancher.DatabaseServer'),
        ),
    ]
