# Generated by Django 2.2.14 on 2020-07-13 04:32

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rancher', '0003_auto_20200701_1547'),
    ]

    operations = [
        migrations.AddField(
            model_name='workload',
            name='image_scan_json',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=dict, editable=False),
        ),
        migrations.AddField(
            model_name='workload',
            name='image_scan_timestamp',
            field=models.DateTimeField(blank=True, editable=False, null=True),
        ),
    ]
