# Generated by Django 2.2.14 on 2020-08-11 02:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rancher', '0004_auto_20200713_1232'),
    ]

    operations = [
        migrations.AlterField(
            model_name='persistentvolume',
            name='uuid',
            field=models.CharField(editable=False, max_length=128),
        ),
        migrations.AlterUniqueTogether(
            name='persistentvolume',
            unique_together={('cluster', 'uuid'), ('cluster', 'volumepath'), ('cluster', 'name')},
        ),
    ]
