# Generated by Django 2.2.14 on 2020-08-11 03:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rancher', '0005_auto_20200811_1011'),
    ]

    operations = [
        migrations.AddField(
            model_name='cluster',
            name='failed_resources',
            field=models.PositiveIntegerField(default=0, editable=False),
        ),
        migrations.AddField(
            model_name='cluster',
            name='refresh_message',
            field=models.TextField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='cluster',
            name='succeed_resources',
            field=models.PositiveIntegerField(default=0, editable=False),
        ),
    ]
