# Generated by Django 2.2.14 on 2020-08-20 06:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rancher', '0006_auto_20200811_1134'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='workload',
            unique_together={('cluster', 'namespace', 'name', 'kind')},
        ),
    ]
