# Generated by Django 2.2.14 on 2020-09-03 03:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rancher', '0008_auto_20200824_1127'),
    ]

    operations = [
        migrations.AddField(
            model_name='cluster',
            name='active_workloads',
            field=models.PositiveIntegerField(default=0, editable=False),
        ),
        migrations.AddField(
            model_name='cluster',
            name='added_by_log',
            field=models.BooleanField(default=False, editable=False),
        ),
        migrations.AddField(
            model_name='cluster',
            name='deleted_workloads',
            field=models.PositiveIntegerField(default=0, editable=False),
        ),
        migrations.AddField(
            model_name='namespace',
            name='active_workloads',
            field=models.PositiveIntegerField(default=0, editable=False),
        ),
        migrations.AddField(
            model_name='namespace',
            name='added_by_log',
            field=models.BooleanField(default=False, editable=False),
        ),
        migrations.AddField(
            model_name='namespace',
            name='deleted_workloads',
            field=models.PositiveIntegerField(default=0, editable=False),
        ),
        migrations.AddField(
            model_name='project',
            name='active_workloads',
            field=models.PositiveIntegerField(default=0, editable=False),
        ),
        migrations.AddField(
            model_name='project',
            name='deleted_workloads',
            field=models.PositiveIntegerField(default=0, editable=False),
        ),
        migrations.AddField(
            model_name='workload',
            name='added_by_log',
            field=models.BooleanField(default=False, editable=False),
        ),
        migrations.AlterField(
            model_name='namespace',
            name='api_version',
            field=models.CharField(editable=False, max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='namespace',
            name='created',
            field=models.DateTimeField(editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='namespace',
            name='modified',
            field=models.DateTimeField(editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='namespace',
            name='project',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='namespaces', to='rancher.Project'),
        ),
        migrations.AlterField(
            model_name='workload',
            name='cmd',
            field=models.CharField(editable=False, max_length=2048, null=True),
        ),
        migrations.AlterField(
            model_name='workload',
            name='project',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='workloads', to='rancher.Project'),
        ),
        migrations.CreateModel(
            name='Container',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('poduid', models.CharField(editable=False, max_length=128)),
                ('containerid', models.CharField(editable=False, max_length=128)),
                ('podip', models.CharField(editable=False, max_length=24, null=True)),
                ('image', models.CharField(editable=False, max_length=128, null=True)),
                ('exitcode', models.CharField(editable=False, max_length=8, null=True)),
                ('ports', models.CharField(editable=False, max_length=1024, null=True)),
                ('envs', models.TextField(editable=False, null=True)),
                ('log', models.BooleanField(default=False, editable=False)),
                ('warning', models.BooleanField(default=False, editable=False)),
                ('error', models.BooleanField(default=False, editable=False)),
                ('status', models.CharField(editable=False, max_length=16, null=True)),
                ('pod_created', models.DateTimeField(editable=False, null=True)),
                ('pod_started', models.DateTimeField(editable=False, null=True)),
                ('container_created', models.DateTimeField(editable=False, null=True)),
                ('container_started', models.DateTimeField(editable=False, null=True)),
                ('container_terminated', models.DateTimeField(editable=False, null=True)),
                ('last_checked', models.DateTimeField(editable=False)),
                ('cluster', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='containers', to='rancher.Cluster')),
                ('namespace', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='containers', to='rancher.Namespace')),
                ('workload', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='containers', to='rancher.Workload')),
            ],
            options={
                'ordering': ['cluster', 'namespace', 'workload', 'container_created'],
                'unique_together': {('workload', 'containerid'), ('cluster', 'workload', 'containerid'), ('cluster', 'containerid'), ('cluster', 'namespace', 'workload', 'containerid')},
            },
        ),
        migrations.CreateModel(
            name='ContainerLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logtime', models.DateTimeField(editable=False)),
                ('level', models.PositiveSmallIntegerField(choices=[(1, 'Trace'), (100, 'Debug'), (200, 'Info'), (300, 'Warning'), (400, 'Error')])),
                ('source', models.CharField(editable=False, max_length=32, null=True)),
                ('message', models.TextField(editable=False)),
                ('archiveid', models.CharField(editable=False, max_length=64, null=True)),
                ('container', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='rancher.Container')),
            ],
            options={
                'ordering': ['container', 'logtime'],
                'unique_together': {('container', 'logtime', 'level')},
                'index_together': {('container', 'level'), ('archiveid',)},
            },
        ),
    ]
