# Generated by Django 2.2.14 on 2020-09-03 05:19

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rancher', '0010_workload_latest_containers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workload',
            name='latest_containers',
            field=django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), size=3), editable=False, null=True, size=None),
        ),
    ]
