# Generated by Django 2.2.16 on 2020-09-10 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rancher', '0011_auto_20200903_1319'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workload',
            name='name',
            field=models.CharField(editable=False, max_length=512),
        ),
    ]
