# Generated by Django 2.2.16 on 2020-09-24 03:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rancher', '0014_auto_20200916_1022'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfigMap',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(editable=False, max_length=128)),
                ('api_version', models.CharField(editable=False, max_length=64)),
                ('modified', models.DateTimeField(editable=False)),
                ('created', models.DateTimeField(editable=False)),
                ('refreshed', models.DateTimeField(auto_now=True)),
                ('cluster', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='configmaps', to='rancher.Cluster')),
                ('namespace', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='configmaps', to='rancher.Namespace')),
            ],
            options={
                'ordering': ['cluster__name', 'namespace__name', 'name'],
                'unique_together': {('cluster', 'namespace', 'name')},
            },
        ),
        migrations.CreateModel(
            name='ConfigMapItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(editable=False, max_length=128)),
                ('value', models.CharField(editable=False, max_length=1024, null=True)),
                ('modified', models.DateTimeField(editable=False)),
                ('created', models.DateTimeField(editable=False)),
                ('refreshed', models.DateTimeField(auto_now=True)),
                ('configmap', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='items', to='rancher.ConfigMap')),
            ],
            options={
                'ordering': ['configmap', 'name'],
                'unique_together': {('configmap', 'name')},
            },
        ),
        migrations.AddField(
            model_name='workloadenv',
            name='configmap',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='workloadenvs', to='rancher.ConfigMap'),
        ),
        migrations.AddField(
            model_name='workloadenv',
            name='configmapitem',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='workloadenvs', to='rancher.ConfigMapItem'),
        ),
    ]
