# Generated by Django 2.2.16 on 2020-09-24 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rancher', '0015_auto_20200924_1118'),
    ]

    operations = [
        migrations.AlterField(
            model_name='configmapitem',
            name='value',
            field=models.TextField(editable=False, max_length=1024, null=True),
        ),
        migrations.AlterField(
            model_name='workloadenv',
            name='value',
            field=models.TextField(editable=False, null=True),
        ),
    ]
