# Generated by Django 2.2.21 on 2021-05-09 23:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rancher', '0017_auto_20200924_1443'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workload',
            name='schedule',
            field=models.CharField(editable=False, max_length=128, null=True),
        ),
    ]
