# Generated by Django 2.2.21 on 2021-05-11 07:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rancher', '0018_auto_20210510_0751'),
    ]

    operations = [
        migrations.AlterField(
            model_name='container',
            name='container_terminated',
            field=models.DateTimeField(db_index=True, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='containerlog',
            name='logtime',
            field=models.DateTimeField(db_index=True, editable=False),
        ),
        migrations.AlterField(
            model_name='workloadvolume',
            name='volume',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='rancher.PersistentVolume'),
        ),
        migrations.AlterField(
            model_name='workloadvolume',
            name='volume_claim',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='rancher.PersistentVolumeClaim'),
        ),
    ]
