# Generated by Django 2.2.21 on 2021-05-20 01:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rancher', '0020_auto_20210514_1415'),
    ]

    operations = [
        migrations.CreateModel(
            name='Harvester',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, editable=False, max_length=64)),
                ('starttime', models.DateTimeField(db_index=True, editable=False)),
                ('endtime', models.DateTimeField(editable=False, null=True)),
                ('status', models.SmallIntegerField(choices=[(1, 'Running'), (-1, 'Failed'), (10, 'Succeed')], db_index=True)),
                ('message', models.TextField(editable=False, null=True)),
            ],
            options={
                'ordering': ['name', 'starttime'],
                'index_together': {('name', 'starttime'), ('name', 'status', 'starttime'), ('status', 'starttime')},
            },
        ),
    ]
