# Generated by Django 2.2.21 on 2021-05-20 03:50

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('rancher', '0021_harvester'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cluster',
            name='failed_resources',
        ),
        migrations.RemoveField(
            model_name='cluster',
            name='refresh_message',
        ),
        migrations.RemoveField(
            model_name='cluster',
            name='refreshed',
        ),
        migrations.RemoveField(
            model_name='cluster',
            name='succeed_resources',
        ),
        migrations.AddField(
            model_name='harvester',
            name='last_heartbeat',
            field=models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='harvester',
            name='status',
            field=models.SmallIntegerField(choices=[(1, 'Running'), (-1, 'Failed'), (10, 'Succeed'), (11, 'Skipped'), (-2, 'Aborted')], db_index=True),
        ),
    ]
