# Generated by Django 2.2.21 on 2021-05-24 03:10

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rancher', '0022_auto_20210520_1150'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContainerImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted', models.DateTimeField(db_index=True, editable=False, null=True)),
                ('account', models.CharField(db_index=True, editable=False, max_length=64, null=True)),
                ('name', models.CharField(editable=False, max_length=128)),
                ('tag', models.CharField(editable=False, max_length=64, null=True)),
                ('workloads', models.PositiveSmallIntegerField(default=0, editable=False)),
                ('scan_status', models.SmallIntegerField(choices=[(0, 'Not Scan'), (-1, 'Scan Failed'), (1, 'No Risk'), (2, 'Low Risk'), (4, 'Middle Risk'), (8, 'High Risk')], db_index=True, default=0, editable=False)),
                ('scaned', models.DateTimeField(editable=False, null=True)),
                ('scan_result', django.contrib.postgres.fields.jsonb.JSONField(editable=False, null=True)),
                ('scan_message', models.TextField(editable=False, null=True)),
                ('added', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['account', 'name', 'tag'],
                'unique_together': {('account', 'name', 'tag')},
            },
        ),
        migrations.AddField(
            model_name='workload',
            name='containerimage',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='weorkloadset', to='rancher.ContainerImage'),
        ),
    ]
