# Generated by Django 2.2.21 on 2021-05-24 07:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rancher', '0024_auto_20210524_1253'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workload',
            name='image_scan_json',
        ),
        migrations.RemoveField(
            model_name='workload',
            name='image_scan_timestamp',
        ),
    ]
