# Generated by Django 2.2.21 on 2021-05-25 02:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rancher', '0025_auto_20210524_1501'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cluster',
            options={'ordering': ['name'], 'verbose_name_plural': '         Clusters'},
        ),
        migrations.AlterModelOptions(
            name='configmap',
            options={'ordering': ['cluster__name', 'namespace__name', 'name'], 'verbose_name_plural': '      Config maps'},
        ),
        migrations.AlterModelOptions(
            name='containerimage',
            options={'ordering': ['account', 'name', 'tag'], 'verbose_name_plural': '   Images'},
        ),
        migrations.AlterModelOptions(
            name='database',
            options={'ordering': ['server', 'name'], 'verbose_name_plural': '    Databases'},
        ),
        migrations.AlterModelOptions(
            name='harvester',
            options={'ordering': ['name', 'starttime'], 'verbose_name_plural': ' Harvesting jobs'},
        ),
        migrations.AlterModelOptions(
            name='namespace',
            options={'ordering': ['cluster__name', 'name'], 'verbose_name_plural': '       Namespaces'},
        ),
        migrations.AlterModelOptions(
            name='persistentvolume',
            options={'ordering': ['cluster__name', 'name'], 'verbose_name_plural': '     Persistent volumes'},
        ),
        migrations.AlterModelOptions(
            name='project',
            options={'ordering': ['cluster__name', 'name'], 'verbose_name_plural': '        Projects'},
        ),
        migrations.AlterModelOptions(
            name='workload',
            options={'ordering': ['cluster__name', 'namespace', 'name'], 'verbose_name_plural': '  Workloads'},
        ),
        migrations.AlterField(
            model_name='containerimage',
            name='scan_status',
            field=models.SmallIntegerField(choices=[(0, 'Not Scan'), (-1, 'Scan Failed'), (1, 'No Risk'), (2, 'Low Risk'), (4, 'Medium Risk'), (8, 'High Risk'), (16, 'Critical Risk')], db_index=True, default=0, editable=False),
        ),
    ]
