# Generated by Django 2.2.21 on 2021-05-25 07:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rancher', '0028_auto_20210525_1446'),
    ]

    operations = [
        migrations.AddField(
            model_name='containerimage',
            name='os',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='images', to='rancher.OperatingSystem'),
        ),
    ]
