# Generated by Django 2.2.21 on 2021-05-26 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rancher', '0029_containerimage_os'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cluster',
            options={'ordering': ['name'], 'verbose_name_plural': '          Clusters'},
        ),
        migrations.AlterModelOptions(
            name='configmap',
            options={'ordering': ['cluster__name', 'namespace__name', 'name'], 'verbose_name_plural': '       Config maps'},
        ),
        migrations.AlterModelOptions(
            name='database',
            options={'ordering': ['server', 'name'], 'verbose_name_plural': '     Databases'},
        ),
        migrations.AlterModelOptions(
            name='namespace',
            options={'ordering': ['cluster__name', 'name'], 'verbose_name_plural': '        Namespaces'},
        ),
        migrations.AlterModelOptions(
            name='persistentvolume',
            options={'ordering': ['cluster__name', 'name'], 'verbose_name_plural': '      Persistent volumes'},
        ),
        migrations.AlterModelOptions(
            name='project',
            options={'ordering': ['cluster__name', 'name'], 'verbose_name_plural': '         Projects'},
        ),
        migrations.AlterModelOptions(
            name='vulnerability',
            options={'ordering': ['os', 'pkgname', 'installedversion', 'vulnerabilityid'], 'verbose_name_plural': '    Vulnerabilities'},
        ),
        migrations.AddField(
            model_name='vulnerability',
            name='affected_images',
            field=models.SmallIntegerField(default=0, editable=False),
        ),
        migrations.AlterField(
            model_name='containerimage',
            name='vulnerabilities',
            field=models.ManyToManyField(editable=False, to='rancher.Vulnerability'),
        ),
    ]
