# Generated by Django 2.2.21 on 2021-05-27 02:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rancher', '0030_auto_20210526_1333'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='containerimage',
            options={'ordering': ['account', 'name', 'tag'], 'verbose_name_plural': ' Images'},
        ),
        migrations.AlterModelOptions(
            name='database',
            options={'ordering': ['server', 'name'], 'verbose_name_plural': '    Databases'},
        ),
        migrations.AlterModelOptions(
            name='harvester',
            options={'ordering': ['name', 'starttime'], 'verbose_name_plural': 'Harvesting jobs'},
        ),
        migrations.AlterModelOptions(
            name='operatingsystem',
            options={'ordering': ['name', 'version'], 'verbose_name_plural': '   OperatingSystems'},
        ),
        migrations.AlterModelOptions(
            name='vulnerability',
            options={'ordering': ['severity', 'pkgname', 'installedversion', 'vulnerabilityid'], 'verbose_name_plural': '  Vulnerabilities'},
        ),
        migrations.AlterModelOptions(
            name='workload',
            options={'ordering': ['cluster__name', 'namespace', 'name'], 'verbose_name_plural': '     Workloads'},
        ),
        migrations.AddField(
            model_name='operatingsystem',
            name='criticals',
            field=models.SmallIntegerField(default=0, editable=False),
        ),
        migrations.AddField(
            model_name='operatingsystem',
            name='highs',
            field=models.SmallIntegerField(default=0, editable=False),
        ),
        migrations.AddField(
            model_name='operatingsystem',
            name='images',
            field=models.SmallIntegerField(default=0, editable=False),
        ),
        migrations.AddField(
            model_name='operatingsystem',
            name='lows',
            field=models.SmallIntegerField(default=0, editable=False),
        ),
        migrations.AddField(
            model_name='operatingsystem',
            name='mediums',
            field=models.SmallIntegerField(default=0, editable=False),
        ),
        migrations.AddField(
            model_name='vulnerability',
            name='affected_oss',
            field=models.SmallIntegerField(default=0, editable=False),
        ),
        migrations.AddField(
            model_name='vulnerability',
            name='oss',
            field=models.ManyToManyField(editable=False, to='rancher.OperatingSystem'),
        ),
        migrations.AlterField(
            model_name='containerimage',
            name='os',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='containerimages', to='rancher.OperatingSystem'),
        ),
        migrations.AlterField(
            model_name='vulnerability',
            name='vulnerabilityid',
            field=models.CharField(editable=False, max_length=128, unique=True),
        ),
        migrations.AlterUniqueTogether(
            name='vulnerability',
            unique_together=set(),
        ),
        migrations.AlterIndexTogether(
            name='vulnerability',
            index_together={('pkgname', 'installedversion'), ('severity', 'pkgname', 'installedversion')},
        ),
        migrations.RemoveField(
            model_name='vulnerability',
            name='os',
        ),
    ]
