# Generated by Django 2.2.21 on 2021-05-27 02:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rancher', '0031_auto_20210527_1008'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='containerimage',
            name='scan_summary',
        ),
        migrations.AddField(
            model_name='containerimage',
            name='criticals',
            field=models.SmallIntegerField(default=0, editable=False),
        ),
        migrations.AddField(
            model_name='containerimage',
            name='highs',
            field=models.SmallIntegerField(default=0, editable=False),
        ),
        migrations.AddField(
            model_name='containerimage',
            name='lows',
            field=models.SmallIntegerField(default=0, editable=False),
        ),
        migrations.AddField(
            model_name='containerimage',
            name='mediums',
            field=models.SmallIntegerField(default=0, editable=False),
        ),
    ]
