# Generated by Django 2.2.21 on 2021-05-28 00:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rancher', '0032_auto_20210527_1037'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vulnerability',
            name='vulnerabilityid',
            field=models.CharField(editable=False, max_length=128),
        ),
        migrations.AlterUniqueTogether(
            name='vulnerability',
            unique_together={('vulnerabilityid', 'pkgname', 'installedversion')},
        ),
    ]
