# Generated by Django 2.2.21 on 2021-06-08 00:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rancher', '0033_auto_20210528_0844'),
    ]

    operations = [
        migrations.AlterField(
            model_name='container',
            name='status',
            field=models.CharField(editable=False, max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='workload',
            name='containerimage',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='workloadset', to='rancher.ContainerImage'),
        ),
    ]
