# Generated by Django 2.2.21 on 2021-06-11 01:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('registers', '0002_auto_20210514_1145'),
        ('rancher', '0035_auto_20210609_1210'),
    ]

    operations = [
        migrations.AddField(
            model_name='workload',
            name='itsystem',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='workloads', to='registers.ITSystem'),
        ),
    ]
