# Generated by Django 2.2.24 on 2021-08-11 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rancher', '0039_auto_20210809_0749'),
    ]

    operations = [
        migrations.AlterField(
            model_name='envscanmodule',
            name='resource_type',
            field=models.PositiveSmallIntegerField(choices=[(20, 'Databases'), (21, 'Postgres'), (22, 'Oracle'), (23, 'MySQL'), (1, 'File System'), (2, 'Blob Storage'), (3, 'REST Api'), (4, 'Email Server'), (11, 'Memcached'), (12, 'Redis'), (30, 'Credential'), (31, 'Database Credential'), (32, 'App Credential'), (33, 'Azure Credential'), (34, 'Blob Credential'), (999, 'Services')]),
        ),
        migrations.AlterField(
            model_name='workload',
            name='resource_scaned',
            field=models.DateTimeField(db_index=True, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='workloaddependency',
            name='dependency_type',
            field=models.PositiveSmallIntegerField(choices=[(21, 'Postgres'), (22, 'Oracle'), (23, 'MySQL'), (1, 'File System'), (2, 'Blob Storage'), (3, 'REST Api'), (4, 'Email Server'), (11, 'Memcached'), (12, 'Redis'), (30, 'Credential'), (31, 'Database Credential'), (32, 'App Credential'), (33, 'Azure Credential'), (34, 'Blob Credential'), (999, 'Image Family')], editable=False),
        ),
        migrations.AlterField(
            model_name='workloadresource',
            name='resource_type',
            field=models.PositiveSmallIntegerField(choices=[(21, 'Postgres'), (22, 'Oracle'), (23, 'MySQL'), (1, 'File System'), (2, 'Blob Storage'), (3, 'REST Api'), (4, 'Email Server'), (11, 'Memcached'), (12, 'Redis'), (30, 'Credential'), (31, 'Database Credential'), (32, 'App Credential'), (33, 'Azure Credential'), (34, 'Blob Credential')], editable=False),
        ),
    ]
