# Generated by Django 2.2.24 on 2021-08-25 02:19

import django.contrib.postgres.fields
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rancher', '0040_auto_20210811_2005'),
    ]

    operations = [
        migrations.AddField(
            model_name='containerimagefamily',
            name='contacts',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.EmailField(max_length=254), null=True, size=None),
        ),
        migrations.AddField(
            model_name='containerimagefamily',
            name='enable_notify',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='containerimagefamily',
            name='enable_warning_msg',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='containerimagefamily',
            name='sourcecode',
            field=models.TextField(blank=True, help_text="The source code of a python module.\n    This module can declare two methods:\n    1. Method 'filter' \n        Parameters:\n            containerlog\n        Return:\n            True if this message need to be send to the developers; otherwise return False\n    2. Method 'loglevel' \n        Parameters:\n            message\n        Return:\n            (Loglevel,True if new message else False) if can determine the message's  loglevel; otherwise return None\n", null=True),
        ),
        migrations.AlterField(
            model_name='containerimagefamily',
            name='config',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=dict),
        ),
    ]
