# Generated by Django 3.2.12 on 2022-03-31 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rancher', '0041_auto_20210825_1019'),
    ]

    operations = [
        migrations.AlterField(
            model_name='containerimage',
            name='scan_result',
            field=models.JSONField(editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='containerimagefamily',
            name='config',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='containerimagefamily',
            name='sourcecode',
            field=models.TextField(blank=True, help_text="The source code of a python module.\n    This module can declare two methods:\n    1. Method 'filter'\n        Parameters:\n            containerlog\n        Return:\n            True if this message need to be send to the developers; otherwise return False\n    2. Method 'loglevel'\n        Parameters:\n            message\n        Return:\n            (Loglevel,True if new message else False) if can determine the message's  loglevel; otherwise return None\n", null=True),
        ),
        migrations.AlterField(
            model_name='vulnerability',
            name='scan_result',
            field=models.JSONField(editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='workload',
            name='suspend',
            field=models.BooleanField(editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='workloaddependenttree',
            name='restree',
            field=models.JSONField(editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='workloaddependenttree',
            name='wltree',
            field=models.JSONField(editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='workloadresource',
            name='properties',
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='workloadvolume',
            name='other_config',
            field=models.JSONField(null=True),
        ),
    ]
