apiVersion: batch/v1
kind: CronJob
metadata:
  name: itassets-cronjob
spec:
  # AWST: 21:01, Mon-Fri
  schedule: '1 13 * * 1-5'
  suspend: true # Remove after new cluster is whitelisted.
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: itassets-cronjob
              args: ['manage.py', 'check_cost_centre_managers']
              envFrom:
                - secretRef:
                    name: itassets-env-prod
