# Generated by Django 2.2.24 on 2021-09-06 01:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organisation', '0007_auto_20210906_0910'),
        ('registers', '0002_auto_20210514_1145'),
    ]

    operations = [
        migrations.AddField(
            model_name='changerequest',
            name='sme',
            field=models.ForeignKey(blank=True, help_text='Optional subject matter expert for this change', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sme', to='organisation.DepartmentUser', verbose_name='subject matter expert'),
        ),
        migrations.AlterField(
            model_name='changerequest',
            name='status',
            field=models.SmallIntegerField(choices=[(0, 'Draft'), (1, 'Submitted for endorsement'), (7, 'Ready for SME review'), (2, 'Scheduled for CAB'), (3, 'Ready for implementation'), (4, 'Complete'), (5, 'Rolled back'), (6, 'Cancelled')], db_index=True, default=0),
        ),
    ]
