# Generated by Django 2.0.8 on 2018-09-11 08:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registers', '0002_auto_20180911_1656'),
    ]

    operations = [
        migrations.AlterField(
            model_name='changeapproval',
            name='date_approved',
            field=models.DateField(blank=True, help_text='Date change was approved/rejected.', null=True),
        ),
        migrations.AlterField(
            model_name='changerequest',
            name='change_duration',
            field=models.DurationField(blank=True, default=datetime.timedelta(0, 3600), help_text='Amount of time change should take to perform (days hh:mm:ss).', null=True),
        ),
    ]
