# Generated by Django 2.0.8 on 2018-09-11 09:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registers', '0003_auto_20180911_1659'),
    ]

    operations = [
        migrations.AlterField(
            model_name='changerequest',
            name='change_duration',
            field=models.DurationField(blank=True, default=datetime.timedelta(0), help_text='Amount of time change should take to perform (days hh:mm:ss).', null=True),
        ),
    ]
