# Generated by Django 2.2.24 on 2021-10-27 04:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('registers', '0003_auto_20210906_0910'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itsystem',
            name='ah_support',
            field=models.ForeignKey(blank=True, help_text='After-hours support contact', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ah_support', to='organisation.DepartmentUser', verbose_name='after hours support'),
        ),
        migrations.AlterField(
            model_name='itsystem',
            name='bh_support',
            field=models.ForeignKey(blank=True, help_text='Business hours support contact', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bh_support', to='organisation.DepartmentUser', verbose_name='business hours support'),
        ),
        migrations.AlterField(
            model_name='itsystem',
            name='information_custodian',
            field=models.ForeignKey(blank=True, help_text='Information custodian', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='systems_info_custodianed', to='organisation.DepartmentUser'),
        ),
        migrations.AlterField(
            model_name='itsystem',
            name='owner',
            field=models.ForeignKey(blank=True, help_text='IT system owner', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='systems_owned', to='organisation.DepartmentUser', verbose_name='system owner'),
        ),
        migrations.AlterField(
            model_name='itsystem',
            name='technology_custodian',
            field=models.ForeignKey(blank=True, help_text='Technology custodian', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='systems_tech_custodianed', to='organisation.DepartmentUser'),
        ),
    ]
