# Generated by Django 2.0.9 on 2018-10-11 00:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registers', '0003_incident_incidentlog'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='incident',
            name='platforms',
        ),
        migrations.AlterField(
            model_name='incident',
            name='category',
            field=models.PositiveIntegerField(blank=True, choices=[(0, 'Outage'), (1, 'Service degredation'), (2, 'Security')], db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='incident',
            name='detection',
            field=models.PositiveIntegerField(blank=True, choices=[(0, 'Monitoring process'), (1, 'OIM staff report'), (2, 'User/custodian report')], db_index=True, help_text='The method by which the incident was initially detected', null=True),
        ),
        migrations.AlterField(
            model_name='incident',
            name='locations',
            field=models.ManyToManyField(blank=True, help_text='Location(s) affected (leave unselected to imply "all locations")', to='organisation.Location'),
        ),
        migrations.AlterField(
            model_name='incident',
            name='priority',
            field=models.CharField(choices=[('L0', 'Low - L0'), ('L1', 'Moderate - L1'), ('L2', 'High - L2'), ('L3', 'Critical - L3')], db_index=True, max_length=16),
        ),
    ]
