# Generated by Django 2.0.8 on 2018-09-12 01:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registers', '0004_auto_20180911_1703'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='changeapproval',
            name='status',
        ),
    ]
