# Generated by Django 3.2.12 on 2022-03-31 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registers', '0004_auto_20211027_1238'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itsystem',
            name='extra_data',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
