# Generated by Django 2.0.9 on 2018-10-23 03:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('registers', '0005_auto_20181017_1426'),
    ]

    operations = [
        migrations.AlterField(
            model_name='changerequest',
            name='approver',
            field=models.ForeignKey(blank=True, help_text='The person who will approve this change', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='approver', to='organisation.DepartmentUser'),
        ),
        migrations.AlterField(
            model_name='changerequest',
            name='change_type',
            field=models.SmallIntegerField(choices=[(0, 'Normal'), (1, 'Standard'), (2, 'Emergency')], db_index=True, default=0, help_text='The change type'),
        ),
        migrations.AlterField(
            model_name='changerequest',
            name='description',
            field=models.TextField(help_text='A brief description of what the change is for and why it is being undertaken'),
        ),
        migrations.AlterField(
            model_name='changerequest',
            name='implementer',
            field=models.ForeignKey(blank=True, help_text='The person who will implement this change', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='implementer', to='organisation.DepartmentUser'),
        ),
        migrations.AlterField(
            model_name='changerequest',
            name='requester',
            field=models.ForeignKey(blank=True, help_text='The who is person requesting this change', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='requester', to='organisation.DepartmentUser'),
        ),
        migrations.AlterField(
            model_name='changerequest',
            name='standard_change',
            field=models.ForeignKey(blank=True, help_text='Standard change reference (if applicable)', null=True, on_delete=django.db.models.deletion.PROTECT, to='registers.StandardChange'),
        ),
        migrations.AlterField(
            model_name='changerequest',
            name='status',
            field=models.SmallIntegerField(choices=[(0, 'Draft'), (1, 'Submitted'), (2, 'Scheduled'), (3, 'Ready'), (4, 'Complete'), (5, 'Rolled back')], db_index=True, default=0),
        ),
        migrations.AlterField(
            model_name='changerequest',
            name='test_date',
            field=models.DateField(blank=True, help_text='Date on which the change was tested', null=True),
        ),
        migrations.AlterField(
            model_name='changerequest',
            name='title',
            field=models.CharField(help_text='A short summary title for this change', max_length=255),
        ),
    ]
