# Generated by Django 3.2.16 on 2022-11-03 06:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organisation', '0018_alter_location_address'),
        ('registers', '0005_alter_itsystem_extra_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='changerequest',
            name='endorser',
            field=models.ForeignKey(blank=True, help_text='The person who will endorse this change prior to CAB', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='endorser', to='organisation.departmentuser'),
        ),
        migrations.AlterField(
            model_name='changerequest',
            name='implementer',
            field=models.ForeignKey(blank=True, help_text='The person who will implement this change', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='implementer', to='organisation.departmentuser'),
        ),
        migrations.AlterField(
            model_name='changerequest',
            name='requester',
            field=models.ForeignKey(blank=True, help_text='The person who is requesting this change', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='requester', to='organisation.departmentuser'),
        ),
        migrations.AlterField(
            model_name='changerequest',
            name='sme',
            field=models.ForeignKey(blank=True, help_text='Optional subject matter expert for this change', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sme', to='organisation.departmentuser', verbose_name='subject matter expert'),
        ),
        migrations.AlterField(
            model_name='changerequest',
            name='standard_change',
            field=models.ForeignKey(blank=True, help_text='Standard change reference (if applicable)', null=True, on_delete=django.db.models.deletion.SET_NULL, to='registers.standardchange'),
        ),
        migrations.AlterField(
            model_name='itsystem',
            name='cost_centre',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='organisation.costcentre'),
        ),
        migrations.AlterField(
            model_name='itsystem',
            name='org_unit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='organisation.orgunit'),
        ),
        migrations.AlterField(
            model_name='standardchange',
            name='endorser',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='organisation.departmentuser'),
        ),
    ]
