# Generated by Django 2.0.8 on 2018-09-12 01:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registers', '0006_auto_20180912_0916'),
    ]

    operations = [
        migrations.AlterField(
            model_name='changerequest',
            name='description',
            field=models.TextField(),
        ),
    ]
