# Generated by Django 2.0.8 on 2018-09-17 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registers', '0007_auto_20180912_0920'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='changerequest',
            name='change_date',
        ),
        migrations.AddField(
            model_name='changerequest',
            name='change_start',
            field=models.DateField(blank=True, help_text='Date change is planned to begin.', null=True),
        ),
        migrations.AddField(
            model_name='changerequest',
            name='title',
            field=models.CharField(default='titletexthere', max_length=255),
            preserve_default=False,
        ),
    ]
