# Generated by Django 2.0.9 on 2018-10-30 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registers', '0008_auto_20181026_1110'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='changerequest',
            options={'ordering': ('-planned_start',)},
        ),
        migrations.AddField(
            model_name='incident',
            name='pir',
            field=models.FileField(blank=True, help_text='Post-incident review (attachment)', null=True, upload_to='uploads/%Y/%m/%d'),
        ),
        migrations.AlterField(
            model_name='changerequest',
            name='unexpected_issues',
            field=models.BooleanField(default=False, help_text='Unexpected/unplanned issues were encountered during the change'),
        ),
    ]
