# Generated by Django 2.0.9 on 2018-10-31 01:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registers', '0009_auto_20181030_1341'),
    ]

    operations = [
        migrations.AlterField(
            model_name='changerequest',
            name='status',
            field=models.SmallIntegerField(choices=[(0, 'Draft'), (1, 'Submitted for endorsement'), (2, 'Scheduled for CAB'), (3, 'Ready'), (4, 'Complete'), (5, 'Rolled back'), (6, 'Cancelled')], db_index=True, default=0),
        ),
    ]
