# Generated by Django 2.0.8 on 2018-09-17 07:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('registers', '0009_auto_20180917_1527'),
    ]

    operations = [
        migrations.AlterField(
            model_name='standardchange',
            name='approver',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='organisation.DepartmentUser'),
        ),
        migrations.AlterField(
            model_name='standardchange',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='standardchange',
            name='it_system',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='registers.ITSystem'),
        ),
    ]
