# Generated by Django 2.0.9 on 2018-12-19 03:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organisation', '0007_auto_20180829_1733'),
        ('registers', '0010_auto_20181031_0940'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='backup',
            name='computer',
        ),
        migrations.RemoveField(
            model_name='backup',
            name='cost_centre',
        ),
        migrations.RemoveField(
            model_name='backup',
            name='org_unit',
        ),
        migrations.RemoveField(
            model_name='businessfunction',
            name='services',
        ),
        migrations.RemoveField(
            model_name='businessprocess',
            name='functions',
        ),
        migrations.AlterUniqueTogether(
            name='processitsystemrelationship',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='processitsystemrelationship',
            name='itsystem',
        ),
        migrations.RemoveField(
            model_name='processitsystemrelationship',
            name='process',
        ),
        migrations.RemoveField(
            model_name='itsystem',
            name='access_display',
        ),
        migrations.RemoveField(
            model_name='itsystem',
            name='alt_processing',
        ),
        migrations.RemoveField(
            model_name='itsystem',
            name='authentication_display',
        ),
        migrations.RemoveField(
            model_name='itsystem',
            name='availability_display',
        ),
        migrations.RemoveField(
            model_name='itsystem',
            name='backup_info',
        ),
        migrations.RemoveField(
            model_name='itsystem',
            name='capability',
        ),
        migrations.RemoveField(
            model_name='itsystem',
            name='contingency_plan',
        ),
        migrations.RemoveField(
            model_name='itsystem',
            name='contingency_plan_last_tested',
        ),
        migrations.RemoveField(
            model_name='itsystem',
            name='contingency_plan_status',
        ),
        migrations.RemoveField(
            model_name='itsystem',
            name='critical_period',
        ),
        migrations.RemoveField(
            model_name='itsystem',
            name='criticality',
        ),
        migrations.RemoveField(
            model_name='itsystem',
            name='criticality_display',
        ),
        migrations.RenameField(
            model_name='itsystem', old_name='custodian', new_name='technology_custodian',
        ),
        migrations.RenameField(
            model_name='itsystem', old_name='data_custodian', new_name='information_custodian',
        ),
        migrations.RemoveField(
            model_name='itsystem',
            name='function',
        ),
        migrations.RemoveField(
            model_name='itsystem',
            name='legal_need_to_retain',
        ),
        migrations.RemoveField(
            model_name='itsystem',
            name='mtd',
        ),
        migrations.RemoveField(
            model_name='itsystem',
            name='notes',
        ),
        migrations.RemoveField(
            model_name='itsystem',
            name='other_projects',
        ),
        migrations.RemoveField(
            model_name='itsystem',
            name='point_of_truth',
        ),
        migrations.RemoveField(
            model_name='itsystem',
            name='post_recovery',
        ),
        migrations.RemoveField(
            model_name='itsystem',
            name='recovery_docs',
        ),
        migrations.RemoveField(
            model_name='itsystem',
            name='request_access',
        ),
        migrations.RemoveField(
            model_name='itsystem',
            name='risks',
        ),
        migrations.RemoveField(
            model_name='itsystem',
            name='rpo',
        ),
        migrations.RemoveField(
            model_name='itsystem',
            name='rto',
        ),
        migrations.RemoveField(
            model_name='itsystem',
            name='schema_url',
        ),
        migrations.RemoveField(
            model_name='itsystem',
            name='sla',
        ),
        migrations.RemoveField(
            model_name='itsystem',
            name='status_display',
        ),
        migrations.RemoveField(
            model_name='itsystem',
            name='status_html',
        ),
        migrations.RemoveField(
            model_name='itsystem',
            name='system_creation_date',
        ),
        migrations.RemoveField(
            model_name='itsystem',
            name='system_health',
        ),
        migrations.RemoveField(
            model_name='itsystem',
            name='system_type_display',
        ),
        migrations.RemoveField(
            model_name='itsystem',
            name='technical_recov',
        ),
        migrations.RemoveField(
            model_name='itsystem',
            name='unique_evidence',
        ),
        migrations.RemoveField(
            model_name='itsystem',
            name='use',
        ),
        migrations.RemoveField(
            model_name='itsystem',
            name='variation_iscp',
        ),
        migrations.RemoveField(
            model_name='itsystem',
            name='vulnerability_docs',
        ),
        migrations.RemoveField(
            model_name='itsystem',
            name='workaround',
        ),
        migrations.AddField(
            model_name='itsystem',
            name='application_server',
            field=models.TextField(blank=True, help_text='Application server(s) that host this system'),
        ),
        migrations.AddField(
            model_name='itsystem',
            name='backups',
            field=models.PositiveIntegerField(blank=True, choices=[(1, 'Point in time database with daily local'), (2, 'Daily local'), (3, 'Vendor-managed')], help_text='Data backup arrangements for this system', null=True),
        ),
        migrations.AddField(
            model_name='itsystem',
            name='emergency_operations',
            field=models.BooleanField(default=False, help_text='System is used for emergency operations'),
        ),
        migrations.AddField(
            model_name='itsystem',
            name='network_storage',
            field=models.TextField(blank=True, help_text='Network storage location(s) used by this system'),
        ),
        migrations.AddField(
            model_name='itsystem',
            name='online_bookings',
            field=models.BooleanField(default=False, help_text='System is used for online bookings'),
        ),
        migrations.AddField(
            model_name='itsystem',
            name='recovery_category',
            field=models.PositiveIntegerField(blank=True, choices=[(1, 'MTD: 1+ week; RTO: 5+ days'), (2, 'MTD: 72 hours; RTO: 48 hours'), (3, 'MTD: 8 hours; RTO: 4 hours')], help_text='The recovery requirements for this system', null=True),
        ),
        migrations.AddField(
            model_name='itsystem',
            name='seasonality',
            field=models.PositiveIntegerField(blank=True, choices=[(1, 'Bushfire season'), (2, 'End of financial year'), (3, 'Annual reporting'), (4, 'School holidays')], help_text='Season/period when this system is most important', null=True),
        ),
        migrations.AddField(
            model_name='itsystem',
            name='status_url',
            field=models.URLField(blank=True, help_text='URL to status/uptime info', max_length=2048, null=True, verbose_name='status URL'),
        ),
        migrations.AddField(
            model_name='itsystem',
            name='visitor_safety',
            field=models.BooleanField(default=False, help_text='System is used for visitor safety'),
        ),
        migrations.AlterField(
            model_name='itsystem',
            name='availability',
            field=models.PositiveIntegerField(blank=True, choices=[(1, '24/7/365'), (2, 'Business hours')], help_text='Expected availability for this IT System', null=True),
        ),
        migrations.AlterField(
            model_name='itsystem',
            name='hardwares',
            field=models.ManyToManyField(blank=True, help_text='[DEPRECATED] Hardware that is used to provide this system', to='registers.ITSystemHardware', verbose_name='hardware'),
        ),
        migrations.AlterField(
            model_name='itsystem',
            name='owner',
            field=models.ForeignKey(help_text='IT system owner', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='systems_owned', to='organisation.DepartmentUser'),
        ),
        migrations.AlterField(
            model_name='itsystem',
            name='system_reqs',
            field=models.TextField(blank=True, help_text='A written description of the requirements to use the system (e.g. web browser version)', verbose_name='system requirements'),
        ),
        migrations.AlterField(
            model_name='itsystem',
            name='user_notification',
            field=models.EmailField(blank=True, help_text='Email address for notification of system incidents', max_length=254, null=True),
        ),
        migrations.DeleteModel(
            name='Backup',
        ),
        migrations.DeleteModel(
            name='BusinessFunction',
        ),
        migrations.DeleteModel(
            name='BusinessProcess',
        ),
        migrations.DeleteModel(
            name='BusinessService',
        ),
        migrations.DeleteModel(
            name='ProcessITSystemRelationship',
        ),
    ]
