# Generated by Django 2.0.9 on 2018-12-19 04:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('registers', '0011_auto_20181219_1140'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='itsystem',
            name='preferred_contact',
        ),
        migrations.AlterField(
            model_name='itsystem',
            name='access',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Public Internet'), (2, 'Authenticated Extranet'), (3, 'Corporate Network'), (4, 'Local System (Networked)'), (5, 'Local System (Standalone)')], default=3, help_text='The network upon which this system is accessible.', null=True),
        ),
        migrations.AlterField(
            model_name='itsystem',
            name='authentication',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Domain/application Credentials'), (2, 'Single Sign On'), (3, 'Externally Managed')], default=1, help_text='The method by which users authenticate themselve to the system.', null=True),
        ),
        migrations.AlterField(
            model_name='itsystem',
            name='information_custodian',
            field=models.ForeignKey(blank=True, help_text='Information custodian', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='systems_info_custodianed', to='organisation.DepartmentUser'),
        ),
        migrations.AlterField(
            model_name='itsystem',
            name='technology_custodian',
            field=models.ForeignKey(help_text='Technology custodian', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='systems_tech_custodianed', to='organisation.DepartmentUser'),
        ),
    ]
