# Generated by Django 2.0.8 on 2018-09-19 03:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('registers', '0011_auto_20180918_1213'),
    ]

    operations = [
        migrations.AlterField(
            model_name='changerequest',
            name='it_system',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='registers.ITSystem'),
        ),
    ]
