# Generated by Django 2.0.8 on 2018-09-19 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registers', '0012_auto_20180919_1133'),
    ]

    operations = [
        migrations.AlterField(
            model_name='changerequest',
            name='submission_date',
            field=models.DateTimeField(help_text='Date change was submitted.'),
        ),
    ]
