# Generated by Django 2.0.8 on 2018-09-20 02:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registers', '0013_auto_20180919_1308'),
    ]

    operations = [
        migrations.RenameField(
            model_name='changerequest',
            old_name='implementer',
            new_name='implementor',
        ),
    ]
