# Generated by Django 2.0.8 on 2018-09-20 08:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('registers', '0014_auto_20180920_1050'),
    ]

    operations = [
        migrations.AddField(
            model_name='changerequest',
            name='standard_change',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='registers.StandardChange'),
        ),
    ]
