# Generated by Django 2.0.8 on 2018-09-20 08:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registers', '0015_changerequest_standard_change'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='changerequest',
            name='standard_change',
        ),
    ]
