# Generated by Django 2.0.9 on 2019-01-09 01:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registers', '0016_auto_20190107_1513'),
    ]

    operations = [
        migrations.AddField(
            model_name='changerequest',
            name='reference_url',
            field=models.URLField(blank=True, help_text='URL to external reference (discusssion, records, etc.)', max_length=2048, null=True, verbose_name='reference URL'),
        ),
    ]
