# Generated by Django 2.1.5 on 2019-02-04 07:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organisation', '0009_location_ascender_code'),
        ('registers', '0017_changerequest_reference_url'),
    ]

    operations = [
        migrations.RenameField(
            model_name='standardchange',
            old_name='approver',
            new_name='endorser',
        ),
        migrations.RenameField(
            model_name='changerequest',
            old_name='approver',
            new_name='endorser',
        ),
    ]
