# Generated by Django 2.0.8 on 2018-09-28 01:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registers', '0017_auto_20180927_1513'),
    ]

    operations = [
        migrations.AddField(
            model_name='changeapproval',
            name='type_of_approval',
            field=models.SmallIntegerField(choices=[(0, 'Email'), (1, 'Navigation'), (2, 'Other')], default=0),
        ),
    ]
