# Generated by Django 2.1.5 on 2019-02-12 01:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('registers', '0018_auto_20190204_1504'),
    ]

    operations = [
        migrations.AlterField(
            model_name='changerequest',
            name='endorser',
            field=models.ForeignKey(blank=True, help_text='The person who will endorse this change prior to CAB', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='endorser', to='organisation.DepartmentUser'),
        ),
    ]
