# Generated by Django 2.0.8 on 2018-09-28 02:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registers', '0018_changeapproval_type_of_approval'),
    ]

    operations = [
        migrations.AddField(
            model_name='changerequest',
            name='completed_date',
            field=models.DateTimeField(blank=True, help_text='Date change was completed.', null=True),
        ),
    ]
