# Generated by Django 2.1.7 on 2019-02-18 02:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registers', '0019_auto_20190212_0913'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itsystem',
            name='documentation',
            field=models.CharField(blank=True, help_text='A link/URL to end-user documentation', max_length=2048, null=True),
        ),
        migrations.AlterField(
            model_name='itsystem',
            name='technical_documentation',
            field=models.CharField(blank=True, help_text='A link/URL to technical documentation', max_length=2048, null=True),
        ),
    ]
