# Generated by Django 2.1.7 on 2019-05-14 02:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registers', '0021_changerequest_test_result_docs'),
    ]

    operations = [
        migrations.AddField(
            model_name='itsystem',
            name='decommission_date',
            field=models.DateField(blank=True, help_text='Date on which the IT system was decommissioned', null=True),
        ),
        migrations.AddField(
            model_name='itsystem',
            name='retention_comments',
            field=models.TextField(blank=True, help_text='Comments/notes related to retention and disposal', null=True, verbose_name='comments'),
        ),
        migrations.AddField(
            model_name='itsystem',
            name='retention_disposal_action',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Retain in agency - migrate records and maintain for the life of Agency.'), (2, 'Required as State Archive - retain in Agency. Migrate records to new database or transfer to SRO when superseded.'), (3, 'Destroy - destroy datasets when superseded. Migrate records and maintain for life of agency.'), (4, 'Destroy - retain 12 months after data migration and decommission (may retain for reference).')], null=True, verbose_name='Retention and disposal action'),
        ),
        migrations.AddField(
            model_name='itsystem',
            name='retention_reference_no',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Retention/disposal reference no.', max_digits=12, null=True),
        ),
    ]
