# Generated by Django 2.1.7 on 2019-05-15 02:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registers', '0022_auto_20190514_1026'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itsystem',
            name='retention_reference_no',
            field=models.CharField(blank=True, help_text='Retention/disposal reference no.', max_length=256, null=True),
        ),
    ]
