# Generated by Django 2.1.7 on 2019-05-23 01:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registers', '0023_auto_20190515_1044'),
    ]

    operations = [
        migrations.RenameField(
            model_name='itsystem',
            old_name='decommission_date',
            new_name='defunct_date',
        ),
    ]
