# Generated by Django 2.1.11 on 2019-09-03 02:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registers', '0026_auto_20190620_1423'),
    ]

    operations = [
        migrations.AddField(
            model_name='changerequest',
            name='post_complete_email_date',
            field=models.DateField(blank=True, help_text='Date on which the implementer was emailed about completion', null=True),
        ),
    ]
