# Generated by Django 2.2.14 on 2020-07-06 04:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registers', '0027_changerequest_post_complete_email_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='itsystem',
            name='hardwares',
        ),
        migrations.DeleteModel(
            name='ITSystemHardware',
        ),
    ]
