# Generated by Django 2.2.16 on 2020-09-09 03:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registers', '0030_auto_20200709_1224'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='incidentlog',
            name='incident',
        ),
        migrations.AlterUniqueTogether(
            name='itsystemdependency',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='itsystemdependency',
            name='dependency',
        ),
        migrations.RemoveField(
            model_name='itsystemdependency',
            name='itsystem',
        ),
        migrations.DeleteModel(
            name='Incident',
        ),
        migrations.DeleteModel(
            name='IncidentLog',
        ),
        migrations.DeleteModel(
            name='ITSystemDependency',
        ),
    ]
