# Generated by Django 2.2.16 on 2020-11-06 04:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('registers', '0032_auto_20201009_1054'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itsystem',
            name='owner',
            field=models.ForeignKey(blank=True, help_text='IT system owner', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='systems_owned', to='organisation.DepartmentUser'),
        ),
        migrations.AlterField(
            model_name='itsystem',
            name='technology_custodian',
            field=models.ForeignKey(blank=True, help_text='Technology custodian', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='systems_tech_custodianed', to='organisation.DepartmentUser'),
        ),
    ]
