# Generated by Django 2.2.16 on 2021-01-22 04:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registers', '0033_auto_20201106_1202'),
    ]

    operations = [
        migrations.AddField(
            model_name='itsystem',
            name='infrastructure_location',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, 'On premises'), (2, 'Azure cloud'), (3, 'AWS cloud'), (4, 'Other provider cloud')], help_text='The primary location of the infrastructure on which this system runs', null=True),
        ),
    ]
