# Generated by Django 2.2.16 on 2021-02-10 05:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registers', '0034_itsystem_infrastructure_location'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UserGroup',
            new_name='ITSystemUserGroup',
        ),
    ]
