apiVersion: batch/v1
kind: CronJob
metadata:
  name: itassets-cronjob
spec:
  # Every minute
  schedule: '* * * * *'
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: itassets-cronjob
              args: ['manage.py', 'department_users_signins', '--logging']
              envFrom:
                - secretRef:
                    name: itassets-env-prod
