apiVersion: batch/v1
kind: CronJob
metadata:
  name: itassets-cronjob
spec:
  # AWST: 23:01, Wed & Sat
  schedule: '1 15 * * 3,6'
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: itassets-cronjob
              args: ['manage.py', 'site_storage_upload']
              envFrom:
                - secretRef:
                    name: itassets-env-prod
