# Generated by Django 2.0.6 on 2018-10-03 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LicensingRule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=256)),
                ('publisher_name', models.CharField(max_length=256)),
                ('regex', models.CharField(max_length=2048)),
                ('license', models.SmallIntegerField(choices=[(1, 'Freeware'), (2, 'Open Source'), (3, 'Commercial - To be decommissioned'), (4, 'Commercial - License required'), (5, 'Commercial - Managed by OIM')])),
            ],
        ),
    ]
