# Generated by Django 2.0.6 on 2018-10-05 06:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organisation', '0007_auto_20180829_1733'),
        ('tracking', '0002_licensingrule'),
    ]

    operations = [
        migrations.AddField(
            model_name='computer',
            name='date_ad_created',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='computer',
            name='date_pdq_last_seen',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='computer',
            name='last_login',
            field=models.ForeignKey(blank=True, help_text='User last seen logged on', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='computers_last_login', to='organisation.DepartmentUser'),
        ),
    ]
