# Generated by Django 2.0.6 on 2018-10-08 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0003_auto_20181005_1432'),
    ]

    operations = [
        migrations.AddField(
            model_name='computer',
            name='pdq_id',
            field=models.PositiveIntegerField(null=True, unique=True),
        ),
    ]
