# Generated by Django 2.2.16 on 2020-09-08 04:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0004_computer_pdq_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='computer',
            name='ec2_instance',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tracking.EC2Instance', verbose_name='EC2 instance'),
        ),
        migrations.AlterField(
            model_name='computer',
            name='location',
            field=models.ForeignKey(blank=True, help_text='Physical location', null=True, on_delete=django.db.models.deletion.SET_NULL, to='organisation.Location'),
        ),
        migrations.AlterField(
            model_name='computer',
            name='managed_by',
            field=models.ForeignKey(blank=True, help_text='"Official" device owner/manager (set in AD).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='computers_managed', to='organisation.DepartmentUser'),
        ),
        migrations.AlterField(
            model_name='computer',
            name='probable_owner',
            field=models.ForeignKey(blank=True, help_text='Automatically-generated "most probable" device owner.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='computers_probably_owned', to='organisation.DepartmentUser'),
        ),
        migrations.AlterField(
            model_name='freshdeskcontact',
            name='du_user',
            field=models.ForeignKey(blank=True, help_text='Department User that is represented by this Freshdesk contact.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='organisation.DepartmentUser'),
        ),
        migrations.AlterField(
            model_name='freshdeskconversation',
            name='du_user',
            field=models.ForeignKey(blank=True, help_text='Department User who is adding to the conversation.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='organisation.DepartmentUser'),
        ),
        migrations.AlterField(
            model_name='freshdeskticket',
            name='du_requester',
            field=models.ForeignKey(blank=True, help_text='Department User who raised the ticket.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='du_requester', to='organisation.DepartmentUser'),
        ),
        migrations.AlterField(
            model_name='freshdeskticket',
            name='du_responder',
            field=models.ForeignKey(blank=True, help_text='Department User to whom the ticket is assigned.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='du_responder', to='organisation.DepartmentUser'),
        ),
        migrations.AlterField(
            model_name='mobile',
            name='registered_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='organisation.DepartmentUser'),
        ),
    ]
