# Generated by Django 2.2.16 on 2020-12-07 01:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0005_auto_20200908_1207'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='computer',
            name='cost_centre',
        ),
        migrations.RemoveField(
            model_name='computer',
            name='extra_data',
        ),
        migrations.RemoveField(
            model_name='computer',
            name='org_unit',
        ),
        migrations.RemoveField(
            model_name='ec2instance',
            name='cost_centre',
        ),
        migrations.RemoveField(
            model_name='ec2instance',
            name='extra_data',
        ),
        migrations.RemoveField(
            model_name='ec2instance',
            name='org_unit',
        ),
        migrations.RemoveField(
            model_name='mobile',
            name='cost_centre',
        ),
        migrations.RemoveField(
            model_name='mobile',
            name='extra_data',
        ),
        migrations.RemoveField(
            model_name='mobile',
            name='org_unit',
        ),
    ]
