# Generated by Django 2.0.9 on 2019-01-23 10:16

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('status', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='host',
            name='backup_info',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='host',
            name='backup_status',
            field=models.SmallIntegerField(choices=[(0, 'N/A'), (1, 'Failure'), (2, 'Unhealthy'), (3, 'OK')], default=0),
        ),
        migrations.AlterField(
            model_name='host',
            name='monitor_info',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='host',
            name='monitor_status',
            field=models.SmallIntegerField(choices=[(0, 'N/A'), (1, 'Failure'), (2, 'Unhealthy'), (3, 'OK')], default=0),
        ),
        migrations.AlterField(
            model_name='host',
            name='patching_info',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='host',
            name='patching_status',
            field=models.SmallIntegerField(choices=[(0, 'N/A'), (1, 'Failure'), (2, 'Unhealthy'), (3, 'OK')], default=0),
        ),
        migrations.AlterField(
            model_name='host',
            name='vulnerability_info',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='host',
            name='vulnerability_status',
            field=models.SmallIntegerField(choices=[(0, 'N/A'), (1, 'Failure'), (2, 'Unhealthy'), (3, 'OK')], default=0),
        ),
    ]
