# Generated by Django 2.0.9 on 2019-01-25 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('status', '0002_auto_20190123_1816'),
    ]

    operations = [
        migrations.AddField(
            model_name='host',
            name='backup_url',
            field=models.URLField(max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='host',
            name='monitor_url',
            field=models.URLField(max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='host',
            name='patching_url',
            field=models.URLField(max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='host',
            name='vulnerability_url',
            field=models.URLField(max_length=256, null=True),
        ),
    ]
