# Generated by Django 2.0.9 on 2019-01-30 03:15

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('status', '0003_auto_20190125_1513'),
    ]

    operations = [
        migrations.CreateModel(
            name='HostStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('ping_status', models.SmallIntegerField(choices=[(0, 'N/A'), (1, 'Failure'), (2, 'Unhealthy'), (3, 'OK')], default=0)),
                ('monitor_status', models.SmallIntegerField(choices=[(0, 'N/A'), (1, 'Failure'), (2, 'Unhealthy'), (3, 'OK')], default=0)),
                ('monitor_info', django.contrib.postgres.fields.jsonb.JSONField(default=dict)),
                ('monitor_url', models.URLField(max_length=256, null=True)),
                ('vulnerability_status', models.SmallIntegerField(choices=[(0, 'N/A'), (1, 'Failure'), (2, 'Unhealthy'), (3, 'OK')], default=0)),
                ('vulnerability_info', django.contrib.postgres.fields.jsonb.JSONField(default=dict)),
                ('vulnerability_url', models.URLField(max_length=256, null=True)),
                ('backup_status', models.SmallIntegerField(choices=[(0, 'N/A'), (1, 'Failure'), (2, 'Unhealthy'), (3, 'OK')], default=0)),
                ('backup_info', django.contrib.postgres.fields.jsonb.JSONField(default=dict)),
                ('backup_url', models.URLField(max_length=256, null=True)),
                ('patching_status', models.SmallIntegerField(choices=[(0, 'N/A'), (1, 'Failure'), (2, 'Unhealthy'), (3, 'OK')], default=0)),
                ('patching_info', django.contrib.postgres.fields.jsonb.JSONField(default=dict)),
                ('patching_url', models.URLField(max_length=256, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='host',
            name='backup_info',
        ),
        migrations.RemoveField(
            model_name='host',
            name='backup_status',
        ),
        migrations.RemoveField(
            model_name='host',
            name='backup_url',
        ),
        migrations.RemoveField(
            model_name='host',
            name='monitor_info',
        ),
        migrations.RemoveField(
            model_name='host',
            name='monitor_status',
        ),
        migrations.RemoveField(
            model_name='host',
            name='monitor_url',
        ),
        migrations.RemoveField(
            model_name='host',
            name='patching_info',
        ),
        migrations.RemoveField(
            model_name='host',
            name='patching_status',
        ),
        migrations.RemoveField(
            model_name='host',
            name='patching_url',
        ),
        migrations.RemoveField(
            model_name='host',
            name='ping_scan_range',
        ),
        migrations.RemoveField(
            model_name='host',
            name='ping_status',
        ),
        migrations.RemoveField(
            model_name='host',
            name='vulnerability_info',
        ),
        migrations.RemoveField(
            model_name='host',
            name='vulnerability_status',
        ),
        migrations.RemoveField(
            model_name='host',
            name='vulnerability_url',
        ),
        migrations.AddField(
            model_name='scanrange',
            name='enabled',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='scanrange',
            name='range',
            field=models.CharField(max_length=2048),
        ),
        migrations.AddField(
            model_name='hoststatus',
            name='host',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='statuses', to='status.Host'),
        ),
        migrations.AddField(
            model_name='hoststatus',
            name='ping_scan_range',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hosts', to='status.ScanRange'),
        ),
    ]
