# Generated by Django 2.0.9 on 2019-01-30 07:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('status', '0004_auto_20190130_1115'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScanPlugin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('plugin', models.CharField(choices=[('monitor_prtg', 'Monitor - PRTG'), ('vulnerability_nessus', 'Vulnerability - Nessus'), ('backup_acronis', 'Backup - Acronis'), ('backup_aws', 'Backup - AWS snapshots'), ('backup_azure', 'Backup - Azure snapshots'), ('backup_veeam', 'Backup - Veeam'), ('backup_restic', 'Backup - Restic'), ('patching_oms', 'Patching - Azure OMS')], max_length=32)),
                ('enabled', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='ScanPluginParameter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('value', models.CharField(blank=True, max_length=2048)),
                ('scan_plugin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='status.ScanPlugin')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='scanpluginparameter',
            unique_together={('scan_plugin', 'name')},
        ),
    ]
