# Generated by Django 2.0.9 on 2019-01-31 06:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('status', '0005_auto_20190130_1532'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='hoststatus',
            options={'verbose_name_plural': 'host statuses'},
        ),
        migrations.AddField(
            model_name='hoststatus',
            name='backup_output',
            field=models.CharField(blank=True, max_length=2048),
        ),
        migrations.AddField(
            model_name='hoststatus',
            name='backup_plugin',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='backup_statuses', to='status.ScanPlugin'),
        ),
        migrations.AddField(
            model_name='hoststatus',
            name='monitor_output',
            field=models.CharField(blank=True, max_length=2048),
        ),
        migrations.AddField(
            model_name='hoststatus',
            name='monitor_plugin',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='monitor_statuses', to='status.ScanPlugin'),
        ),
        migrations.AddField(
            model_name='hoststatus',
            name='patching_output',
            field=models.CharField(blank=True, max_length=2048),
        ),
        migrations.AddField(
            model_name='hoststatus',
            name='patching_plugin',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='patching_statuses', to='status.ScanPlugin'),
        ),
        migrations.AddField(
            model_name='hoststatus',
            name='vulnerability_output',
            field=models.CharField(blank=True, max_length=2048),
        ),
        migrations.AddField(
            model_name='hoststatus',
            name='vulnerability_plugin',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vulnerability_statuses', to='status.ScanPlugin'),
        ),
        migrations.AlterField(
            model_name='scanpluginparameter',
            name='scan_plugin',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='params', to='status.ScanPlugin'),
        ),
    ]
