# Generated by Django 2.0.9 on 2019-02-19 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('status', '0007_auto_20190212_0913'),
    ]

    operations = [
        migrations.AddField(
            model_name='host',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
