# Generated by Django 2.2.10 on 2020-02-17 23:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('status', '0008_host_active'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='host',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='scanplugin',
            options={'ordering': ('name',)},
        ),
        migrations.AlterModelOptions(
            name='scanpluginparameter',
            options={'ordering': ('scan_plugin', 'name')},
        ),
        migrations.AlterField(
            model_name='scanplugin',
            name='plugin',
            field=models.CharField(choices=[('monitor_prtg', 'Monitor - PRTG'), ('vulnerability_nessus', 'Vulnerability - Nessus'), ('backup_acronis', 'Backup - Acronis'), ('backup_aws', 'Backup - AWS snapshots'), ('backup_azure', 'Backup - Azure snapshots'), ('backup_storagesync', 'Backup - Azure Storage Sync Services'), ('backup_phoenix', 'Backup - Druva Phoenix'), ('patching_oms', 'Patching - Azure OMS')], max_length=32),
        ),
    ]
