# Generated by Django 2.2.14 on 2020-07-22 06:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('status', '0010_auto_20200721_1119'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='hoststatus',
            options={'get_latest_by': 'date', 'verbose_name_plural': 'host statuses'},
        ),
    ]
