# Generated by Django 2.2.16 on 2020-10-08 03:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('status', '0011_auto_20200722_1413'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='hoststatus',
            unique_together={('host', 'date')},
        ),
    ]
