# Generated by Django 2.2.16 on 2021-05-05 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('status', '0013_auto_20201009_1030'),
    ]

    operations = [
        migrations.AddField(
            model_name='host',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
