# Generated by Django 2.2.21 on 2021-05-17 00:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('status', '0014_host_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scanplugin',
            name='plugin',
            field=models.CharField(choices=[('monitor_prtg', 'Monitor - PRTG'), ('vulnerability_nessus', 'Vulnerability - Nessus'), ('backup_aws', 'Backup - AWS snapshots'), ('backup_azure', 'Backup - Azure snapshots'), ('backup_storagesync', 'Backup - Azure Storage Sync Services'), ('patching_oms', 'Patching - Azure OMS')], max_length=32),
        ),
    ]
