apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: itassets-postgres-fdw
spec:
  replicas: 1
  minReadySeconds: 10
  serviceName: itassets-postgres-fdw
  template:
    spec:
      containers:
        - name: itassets-postgres-fdw
          image: ghcr.io/dbca-wa/postgres-oracle-fdw:16-3.5
          imagePullPolicy: IfNotPresent
          env:
            - name: TZ
              value: 'Australia/Perth'
            - name: POSTGRES_DB
              value: 'fdw'
          resources:
            requests:
              memory: '128Mi'
              cpu: '10m'
            limits:
              memory: '1Gi'
              cpu: '1000m'
          securityContext:
            runAsNonRoot: true
            runAsUser: 999
            privileged: false
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL
                # NOTE: Postgres pod will not run with a read-only root filesystem.
            readOnlyRootFilesystem: false
      restartPolicy: Always
      automountServiceAccountToken: false
