name: 'Run Django unit tests'

on:
  push:
    branches:
      - main
      - dev
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  run_tests:
    name: Run Django Tests
    runs-on: ubuntu-latest
    permissions:
      contents: read
    env:
      DATABASE_URL: postgis://postgres:postgres@localhost:5432/postgres
      ASCENDER_CREATE_AZURE_AD_LIMIT_DAYS: 14
    services:
      postgres:
        image: postgis/postgis:16-3.5-alpine
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
        ports:
          - 5432:5432
        options: --mount type=tmpfs,destination=/var/lib/postgresql/data --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5
    steps:
      #----------------------------------------------
      # Make use of the Step Security Harden Runner workflow to monitor the build process.
      #----------------------------------------------
      - name: Harden the GitHub runner
        uses: step-security/harden-runner@05e31511f85b41b11d1cf0ef85d0992719546e2c # v2.21.0
        with:
          egress-policy: audit
      #----------------------------------------------
      # Install GDAL into the environment
      #----------------------------------------------
      - name: Install GDAL
        id: install-gdal
        run: |
          sudo apt-get update
          sudo apt-get install gdal-bin libgdal-dev
      #----------------------------------------------
      # Checkout repo
      #----------------------------------------------
      - name: Check out repository
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          fetch-depth: 0
          persist-credentials: false
      #----------------------------------------------
      # Install & configure uv
      #----------------------------------------------
      - name: Install uv
        uses: astral-sh/setup-uv@c771a70e6277c0a99b617c7a806ffedaca235ff9 # v9.0.0
        with:
          python-version: '3.13'
          enable-cache: true
      #----------------------------------------------
      # Install project dependencies
      #----------------------------------------------
      - name: Install dependencies
        run: uv sync
      #----------------------------------------------
      # Run unit tests
      #----------------------------------------------
      - name: Run tests
        run: |
          uv run python manage.py collectstatic
          uv run python manage.py test --noinput --failfast --verbosity 0
