name: 'Scan project for secrets & sensitive information'

on:
  push:
    branches:
      - main
      - dev
  pull_request:
    branches:
      - main

jobs:
  secret-scan:
    name: Scan project for secrets
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Checkout repository
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          fetch-depth: 0
      - name: Secret scanning
        uses: trufflesecurity/trufflehog@d411fff7b8879a62509f3fa98c07f247ac089a51 # v3
        with:
          base: ''
          head: ${{ github.ref_name }}
          extra_args: --only-verified
